# Generated by Django 2.0.6 on 2019-04-26 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        ('Colors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='FinishSurface',
            fields=[
                ('productsubclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.ProductSubClass')),
                ('walls', models.BooleanField(default=False)),
                ('countertops', models.BooleanField(default=False)),
                ('floors', models.BooleanField(default=False)),
                ('cabinet_fronts', models.BooleanField(default=False)),
                ('shower_floors', models.BooleanField(default=False)),
                ('shower_walls', models.BooleanField(default=False)),
                ('exterior_walls', models.BooleanField(default=False)),
                ('exterior_floors', models.BooleanField(default=False)),
                ('covered_walls', models.BooleanField(default=False)),
                ('covered_floors', models.BooleanField(default=False)),
                ('pool_linings', models.BooleanField(default=False)),
                ('bullnose', models.BooleanField(default=False)),
                ('covebase', models.BooleanField(default=False)),
                ('corner_covebase', models.BooleanField(default=False)),
                ('thickness', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('width', models.CharField(blank=True, max_length=50, null=True)),
                ('length', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(max_length=30, null=True)),
                ('lrv', models.CharField(blank=True, max_length=60, null=True)),
                ('cof', models.CharField(max_length=60, null=True)),
                ('install_type', models.CharField(max_length=100, null=True)),
                ('sqft_per_carton', models.CharField(max_length=70, null=True)),
                ('slip_resistant', models.BooleanField(default=False)),
                ('shade', models.CharField(max_length=60, null=True)),
                ('actual_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actuals', to='Colors.Color')),
                ('edge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FinishSurfaces.Edge')),
                ('finish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FinishSurfaces.Finish')),
                ('label_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labels', to='Colors.Color')),
            ],
            bases=('Products.productsubclass',),
        ),
        migrations.CreateModel(
            name='Look',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShadeVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='FinishSurfaces.Material')),
            ],
        ),
        migrations.CreateModel(
            name='SurfaceCoating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coatings', to='FinishSurfaces.Material')),
            ],
        ),
        migrations.CreateModel(
            name='SurfaceTexture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='textures', to='FinishSurfaces.Material')),
            ],
        ),
        migrations.AddField(
            model_name='finishsurface',
            name='look',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FinishSurfaces.Look'),
        ),
        migrations.AddField(
            model_name='finishsurface',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FinishSurfaces.Material'),
        ),
        migrations.AddField(
            model_name='finishsurface',
            name='shade_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FinishSurfaces.ShadeVariation'),
        ),
        migrations.AddField(
            model_name='finishsurface',
            name='sub_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FinishSurfaces.SubMaterial'),
        ),
        migrations.AddField(
            model_name='finishsurface',
            name='surface_coating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FinishSurfaces.SurfaceCoating'),
        ),
        migrations.AddField(
            model_name='finishsurface',
            name='surface_texture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FinishSurfaces.SurfaceTexture'),
        ),
        migrations.AddField(
            model_name='finish',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finishes', to='FinishSurfaces.Material'),
        ),
        migrations.AlterUniqueTogether(
            name='surfacetexture',
            unique_together={('material', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='surfacecoating',
            unique_together={('material', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='submaterial',
            unique_together={('material', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='finish',
            unique_together={('material', 'label')},
        ),
    ]
