# Generated by Django 2.0.6 on 2019-05-03 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishSurface',
            fields=[
                ('productsubclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.ProductSubClass')),
                ('label_color', models.CharField(blank=True, max_length=200, null=True)),
                ('material', models.CharField(max_length=200)),
                ('sub_material', models.CharField(blank=True, max_length=200, null=True)),
                ('finish', models.CharField(blank=True, max_length=200, null=True)),
                ('surface_texture', models.CharField(blank=True, max_length=200, null=True)),
                ('surface_coating', models.CharField(blank=True, max_length=200, null=True)),
                ('look', models.CharField(blank=True, max_length=200, null=True)),
                ('shade_variation', models.CharField(blank=True, max_length=200, null=True)),
                ('shade', models.CharField(max_length=60, null=True)),
                ('walls', models.BooleanField(default=False)),
                ('countertops', models.BooleanField(default=False)),
                ('floors', models.BooleanField(default=False)),
                ('cabinet_fronts', models.BooleanField(default=False)),
                ('shower_floors', models.BooleanField(default=False)),
                ('shower_walls', models.BooleanField(default=False)),
                ('exterior_walls', models.BooleanField(default=False)),
                ('exterior_floors', models.BooleanField(default=False)),
                ('covered_walls', models.BooleanField(default=False)),
                ('covered_floors', models.BooleanField(default=False)),
                ('pool_linings', models.BooleanField(default=False)),
                ('bullnose', models.BooleanField(default=False)),
                ('covebase', models.BooleanField(default=False)),
                ('corner_covebase', models.BooleanField(default=False)),
                ('thickness', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('width', models.CharField(blank=True, max_length=50, null=True)),
                ('length', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=80, null=True)),
                ('shape', models.CharField(blank=True, max_length=80, null=True)),
                ('lrv', models.CharField(blank=True, max_length=60, null=True)),
                ('cof', models.CharField(max_length=60, null=True)),
                ('edge', models.CharField(blank=True, max_length=200, null=True)),
                ('install_type', models.CharField(max_length=100, null=True)),
                ('sqft_per_carton', models.CharField(max_length=70, null=True)),
                ('slip_resistant', models.BooleanField(default=False)),
            ],
            bases=('Products.productsubclass',),
        ),
    ]
