# Generated by Django 2.0.6 on 2019-05-04 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
        ('FinishSurfaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishsurface',
            name='productsubclass_ptr',
        ),
        migrations.AddField(
            model_name='finishsurface',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.Product'),
            preserve_default=False,
        ),
    ]
