# Generated by Django 2.0.6 on 2019-04-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinishSurfaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishsurface',
            name='shape',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='finishsurface',
            name='size',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
