# Generated by Django 2.0.6 on 2019-05-08 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinishSurfaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishsurface',
            name='surface_texture',
        ),
    ]
