# Generated by Django 2.0.6 on 2019-05-08 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinishSurfaces', '0002_remove_finishsurface_surface_texture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishsurface',
            name='shade',
        ),
    ]
