# Generated by Django 3.0.3 on 2020-02-13 22:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
            options={
                'unique_together': {('lat', 'lng')},
            },
        ),
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('centroid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Addresses.Coordinate')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=120)),
                ('address_line_2', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('gmaps_id', models.CharField(max_length=200, unique=True)),
                ('address_string', models.CharField(blank=True, max_length=1000, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=13, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=13, null=True)),
                ('country', models.CharField(blank=True, default='United States of America', max_length=120, null=True)),
                ('state', models.CharField(max_length=120)),
                ('coordinates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Addresses.Coordinate')),
                ('postal_code', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='address', to='Addresses.Zipcode')),
            ],
        ),
    ]
