# Generated by Django 3.0.3 on 2020-03-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='demo',
            field=models.BooleanField(default=False),
        ),
    ]
