# Generated by Django 2.0.6 on 2018-12-05 05:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinate',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
