# Generated by Django 2.2.1 on 2019-09-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_string',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=13, null=True),
        ),
    ]
