# Generated by Django 2.2.1 on 2019-08-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='gmaps_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
