# Generated by Django 2.2.1 on 2019-08-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Addresses', '0002_address_gmaps_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coordinate',
            unique_together={('lat', 'lng')},
        ),
    ]
