# Generated by Django 2.0.6 on 2018-12-05 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Addresses', '0002_coordinate_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zipcode',
            old_name='coordinate',
            new_name='centroid',
        ),
    ]
