# Generated by Django 2.0.6 on 2018-12-03 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Addresses', '0002_auto_20181126_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('coordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Addresses.Coordinate')),
            ],
        ),
    ]
