# Generated by Django 2.0.6 on 2018-12-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addresses', '0003_auto_20181205_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
