# Generated by Django 2.2.1 on 2019-08-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addresses', '0003_auto_20190802_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='gmaps_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
