# Generated by Django 3.0.2 on 2020-01-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperCleaner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgroup_manufacturer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('subgroup_category_name', models.CharField(blank=True, max_length=200, null=True)),
                ('field_name', models.CharField(blank=True, max_length=200, null=True)),
                ('initial_value', models.CharField(blank=True, max_length=200, null=True)),
                ('new_value', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
