# Generated by Django 2.2.1 on 2019-05-15 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Scraper', '0002_scrapersubgroup_cleaned'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperCleaner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(blank=True, max_length=200, null=True)),
                ('initial_value', models.CharField(blank=True, max_length=200, null=True)),
                ('new_value', models.CharField(blank=True, max_length=200, null=True)),
                ('subgroup_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaners', to='Scraper.ScraperSubgroup')),
            ],
        ),
    ]
