# Generated by Django 2.2.1 on 2019-05-15 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScraperCleaner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapercleaner',
            old_name='subgroup_name',
            new_name='subgroup',
        ),
    ]
