# Generated by Django 2.2.1 on 2019-05-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScraperCleaner', '0002_auto_20190514_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapercleaner',
            name='subgroup',
        ),
        migrations.AddField(
            model_name='scrapercleaner',
            name='subgroup_category_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scrapercleaner',
            name='subgroup_manufacturer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
