# Generated by Django 2.2.1 on 2019-05-17 02:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScraperCleaner', '0003_auto_20190514_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapercleaner',
            old_name='field',
            new_name='field_name',
        ),
        migrations.AddField(
            model_name='scrapercleaner',
            name='default_product_pks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='scrapercleaner',
            name='initial_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterUniqueTogether(
            name='scrapercleaner',
            unique_together={('subgroup_manufacturer_name', 'subgroup_category_name', 'field_name', 'new_value')},
        ),
        migrations.RemoveField(
            model_name='scrapercleaner',
            name='initial_value',
        ),
    ]
