# Generated by Django 2.2.1 on 2019-05-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScraperCleaner', '0004_auto_20190516_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapercleaner',
            name='initial_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='scrapercleaner',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='scrapercleaner',
            name='default_product_pks',
        ),
        migrations.RemoveField(
            model_name='scrapercleaner',
            name='initial_values',
        ),
    ]
