# Generated by Django 2.0.6 on 2019-01-16 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Addresses', '0001_initial'),
        ('Plans', '0001_initial'),
        ('Products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('account_owner', models.OneToOneField(limit_choices_to={'is_supplier': True}, on_delete=django.db.models.deletion.CASCADE, related_name='company_account', to=settings.AUTH_USER_MODEL)),
                ('headquarters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Addresses.Address')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='Plans.SupplierPlan')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyShippingLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=120, null=True)),
                ('approved_in_store_seller', models.BooleanField(default=False)),
                ('approved_online_seller', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=10)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Addresses.Address')),
                ('company_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_locations', to='Profiles.CompanyAccount')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('online_ppu', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('units_available', models.IntegerField(default=0, null=True)),
                ('units_per_order', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('for_sale_in_store', models.BooleanField(default=False)),
                ('for_sale_online', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priced', to='Products.Product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priced_products', to='Profiles.CompanyShippingLocation')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='supplierproduct',
            unique_together={('product', 'supplier')},
        ),
    ]
