# Generated by Django 2.2.1 on 2019-07-07 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Plans', '0001_initial'),
        ('Groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RetailerEmployeeProfile',
            fields=[
                ('baseprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Profiles.BaseProfile')),
                ('owner', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='Groups.RetailerCompany')),
            ],
            options={
                'abstract': False,
            },
            bases=('Profiles.baseprofile',),
        ),
        migrations.CreateModel(
            name='ProEmployeeProfile',
            fields=[
                ('baseprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Profiles.BaseProfile')),
                ('owner', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='Groups.ProCompany')),
            ],
            options={
                'abstract': False,
            },
            bases=('Profiles.baseprofile',),
        ),
        migrations.CreateModel(
            name='ConsumerProfile',
            fields=[
                ('baseprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Profiles.BaseProfile')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='Plans.ConsumerPlan')),
            ],
            bases=('Profiles.baseprofile',),
        ),
    ]
