# Generated by Django 2.2.1 on 2019-05-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyshippinglocation',
            name='info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyshippinglocation',
            name='website',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
