# Generated by Django 3.0.2 on 2020-01-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseprofile',
            name='collaborators',
            field=models.ManyToManyField(blank=True, to='Profiles.BaseProfile'),
        ),
    ]
