# Generated by Django 2.0.6 on 2018-07-20 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaccount',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyshippinglocation',
            name='approved_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyaccount',
            name='account_owner',
            field=models.ForeignKey(limit_choices_to={'is_supplier': True}, on_delete=django.db.models.deletion.CASCADE, related_name='company_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyaccount',
            name='headquarters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Addresses.Address'),
        ),
        migrations.AlterField(
            model_name='companyshippinglocation',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Addresses.Address'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='Addresses.Address'),
        ),
    ]
