# Generated by Django 2.0.6 on 2018-11-25 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='account_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyaccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='addresses',
            field=models.ManyToManyField(related_name='addresses', to='Addresses.Address'),
        ),
    ]
