# Generated by Django 3.0 on 2020-01-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseprofile',
            name='collaborators',
            field=models.ManyToManyField(blank=True, to='Profiles.BaseProfile'),
        ),
        migrations.AddField(
            model_name='proemployeeprofile',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='retaileremployeeprofile',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
