# Generated by Django 3.0.3 on 2020-02-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suppliers', '0002_supplierproducttree'),
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieremployeeprofile',
            name='contact_for',
            field=models.ManyToManyField(to='Suppliers.SupplierLocation'),
        ),
    ]
