# Generated by Django 2.0.6 on 2019-05-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyshippinglocation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='storefronts/'),
        ),
    ]
