# Generated by Django 2.0.6 on 2019-01-20 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_account_owner', models.BooleanField(default=False)),
                ('company_account_admin', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='companyaccount',
            name='account_owner',
        ),
        migrations.AddField(
            model_name='companyaccount',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyshippinglocation',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='company_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='Profiles.CompanyAccount'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_supplier': True}, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyshippinglocation',
            name='local_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profiles.EmployeeProfile'),
        ),
    ]
