# Generated by Django 2.0.6 on 2018-10-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyshippinglocation',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
