# Generated by Django 2.0.6 on 2019-04-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
