# Generated by Django 2.0.6 on 2019-01-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_auto_20190120_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='offer_installation',
            field=models.BooleanField(default=False),
        ),
    ]
