# Generated by Django 2.2.1 on 2019-06-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_auto_20190527_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproduct',
            name='product_bb_sku',
            field=models.CharField(max_length=60),
        ),
    ]
