# Generated by Django 2.0.6 on 2018-10-16 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_auto_20181004_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyshippinglocation',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='companyshippinglocation',
            name='lng',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='companyaccount',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='companyshippinglocation',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Addresses.Address'),
        ),
    ]
