# Generated by Django 2.0.6 on 2018-08-08 18:08

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_product_manufacturer_url'),
        ('Profiles', '0002_customerprofile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_products', to='Products.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='customerproject',
            name='products',
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='price_per_unit',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=None, default_currency='USD', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='units_available',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Profiles.CustomerProject'),
        ),
    ]
