# Generated by Django 3.0.3 on 2020-03-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_supplieremployeeprofile_contact_for'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplieremployeeprofile',
            old_name='admin',
            new_name='company_admin',
        ),
        migrations.RenameField(
            model_name='supplieremployeeprofile',
            old_name='owner',
            new_name='company_owner'
        ),
        migrations.AddField(
            model_name='baseprofile',
            name='location_asked',
            field=models.BooleanField(default=False),
        )
    ]
