# Generated by Django 2.0.6 on 2018-07-20 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_auto_20180720_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='account_owner',
            field=models.ForeignKey(limit_choices_to={'is_supplier': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
