# Generated by Django 2.0.6 on 2018-11-25 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_auto_20181125_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyshippinglocation',
            name='approved_in_store_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companyshippinglocation',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Addresses.Address'),
        ),
    ]
