# Generated by Django 3.0.2 on 2020-01-15 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Plans', '0001_initial'),
        ('Profiles', '0002_baseprofile_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerprofile',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Plans.ConsumerPlan'),
        ),
    ]
