# Generated by Django 2.2.1 on 2019-10-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_baseprofile_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
