# Generated by Django 3.0.2 on 2020-02-06 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0023_product_category'),
        ('Profiles', '0003_consumerprofile_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Profiles.ConsumerProfile')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_products', to='Products.Product')),
            ],
            options={
                'unique_together': {('product', 'owner')},
            },
        ),
    ]
