# Generated by Django 2.2.1 on 2019-06-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_auto_20190612_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierproduct',
            old_name='for_sale_in_store',
            new_name='publish_in_store_price',
        ),
        migrations.RenameField(
            model_name='supplierproduct',
            old_name='for_sale_online',
            new_name='publish_online_price',
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='publish_in_store_availability',
            field=models.BooleanField(default=True),
        ),
    ]
