# Generated by Django 2.0.6 on 2019-01-22 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_supplierproduct_offer_installation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyshippinglocation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='companyshippinglocation',
            name='local_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profiles.EmployeeProfile'),
        ),
    ]
