# Generated by Django 2.0.6 on 2018-08-08 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_auto_20180808_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerproduct',
            old_name='application',
            new_name='use',
        ),
    ]
