# Generated by Django 3.0.3 on 2020-03-07 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Addresses', '0002_address_demo'),
        ('Profiles', '0003_auto_20200304_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseprofile',
            name='current_zipcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Addresses.Zipcode'),
        ),
        migrations.AddField(
            model_name='baseprofile',
            name='latest_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Addresses.Coordinate'),
        ),
    ]
