# Generated by Django 2.0.6 on 2018-11-29 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_auto_20181125_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='account_owner',
            field=models.OneToOneField(limit_choices_to={'is_supplier': True}, on_delete=django.db.models.deletion.CASCADE, related_name='company_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
