# Generated by Django 2.2.1 on 2019-10-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_auto_20191002_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
