# Generated by Django 2.0.6 on 2018-10-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_auto_20181015_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyshippinglocation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='companyshippinglocation',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyshippinglocation',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
