# Generated by Django 2.0.6 on 2018-10-17 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0004_auto_20181016_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='account_owner',
            field=models.OneToOneField(limit_choices_to={'is_supplier': True}, on_delete=django.db.models.deletion.CASCADE, related_name='company_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyaccount',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
