# Generated by Django 2.0.6 on 2019-02-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0004_auto_20190121_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaccount',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='companyshippinglocation',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
