# Generated by Django 2.0.6 on 2018-08-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0004_auto_20180808_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierproduct',
            name='price_per_unit_currency',
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='my_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
