# Generated by Django 2.0.6 on 2018-08-12 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0005_auto_20180812_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyshippinglocation',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='companyaccount',
            name='account_owner',
            field=models.OneToOneField(limit_choices_to={'is_supplier': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
