# Generated by Django 2.0.6 on 2018-10-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0005_auto_20181017_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyshippinglocation',
            old_name='approved_seller',
            new_name='approved_online_seller',
        ),
        migrations.RenameField(
            model_name='supplierproduct',
            old_name='for_sale',
            new_name='for_sale_in_store',
        ),
        migrations.RenameField(
            model_name='supplierproduct',
            old_name='price_per_unit',
            new_name='online_ppu',
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='for_sale_online',
            field=models.BooleanField(default=False),
        ),
    ]
