# Generated by Django 2.0.6 on 2019-02-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0005_auto_20190211_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyshippinglocation',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
