# Generated by Django 2.0.6 on 2019-03-14 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0006_auto_20190214_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierproduct',
            old_name='my_price',
            new_name='in_store_ppu',
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='banner_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='lead_time_ts',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
