# Generated by Django 2.0.6 on 2018-11-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0006_auto_20181021_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyshippinglocation',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='companyshippinglocation',
            name='lng',
        ),
        migrations.AddField(
            model_name='companyshippinglocation',
            name='phone_number',
            field=models.CharField(default='none', max_length=10),
            preserve_default=False,
        ),
    ]
