# Generated by Django 2.0.6 on 2019-03-14 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0007_auto_20190314_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierproduct',
            old_name='units_available',
            new_name='sf_available_in_store',
        ),
        migrations.RenameField(
            model_name='supplierproduct',
            old_name='units_per_order',
            new_name='sf_per_unit_order',
        ),
    ]
