# Generated by Django 2.0.6 on 2018-11-14 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0007_auto_20181105_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='headquarters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Addresses.Address'),
        ),
    ]
