# Generated by Django 2.0.6 on 2018-11-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0008_auto_20181113_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='addresses',
            field=models.ManyToManyField(null=True, related_name='addresses', to='Addresses.Address'),
        ),
    ]
