# Generated by Django 2.0.6 on 2019-03-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0008_auto_20190314_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierproduct',
            old_name='in_store_ppu',
            new_name='in_store_ppsf',
        ),
        migrations.RenameField(
            model_name='supplierproduct',
            old_name='online_ppu',
            new_name='online_ppsf',
        ),
    ]
