# Generated by Django 2.0.6 on 2019-03-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0009_auto_20190314_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierproduct',
            old_name='in_store_ppsf',
            new_name='in_store_ppu',
        ),
        migrations.RenameField(
            model_name='supplierproduct',
            old_name='online_ppsf',
            new_name='online_ppu',
        ),
        migrations.RenameField(
            model_name='supplierproduct',
            old_name='sf_available_in_store',
            new_name='units_available_in_store',
        ),
        migrations.RenameField(
            model_name='supplierproduct',
            old_name='sf_per_unit_order',
            new_name='units_per_order',
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='units',
            field=models.CharField(choices=[('SF', 'SF'), ('EACH', 'Each')], default='SF', max_length=10),
        ),
    ]
