# Generated by Django 2.0.6 on 2019-03-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0010_auto_20190314_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproduct',
            name='units_per_order',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
