# Generated by Django 2.0.6 on 2019-03-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0011_auto_20190314_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierproduct',
            old_name='units',
            new_name='unit',
        ),
    ]
