# Generated by Django 2.0.6 on 2019-03-14 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0012_auto_20190314_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierproduct',
            name='unit',
        ),
    ]
