# Generated by Django 3.0.3 on 2020-02-13 22:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profiles', '0001_initial'),
        ('Addresses', '0001_initial'),
        ('Products', '0001_initial'),
        ('Groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=60)),
                ('approved_in_store_seller', models.BooleanField(default=False)),
                ('approved_online_seller', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='storefronts/')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retailer_locations', to='Addresses.Address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_locations', to='Groups.SupplierCompany')),
                ('local_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_locations', to='Profiles.SupplierEmployeeProfile')),
            ],
            options={
                'unique_together': {('nickname', 'company')},
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_available_in_store', models.IntegerField(default=0, null=True)),
                ('units_per_order', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('product_bb_sku', models.CharField(max_length=60)),
                ('publish_in_store_availability', models.BooleanField(default=True)),
                ('publish_in_store_price', models.BooleanField(default=False)),
                ('publish_online_price', models.BooleanField(default=False)),
                ('in_store_ppu', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('online_ppu', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('lead_time_ts', models.DurationField(blank=True, default=datetime.timedelta(0), null=True)),
                ('offer_installation', models.BooleanField(default=False)),
                ('banner_item', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Suppliers.SupplierLocation')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priced', to='Products.Product')),
            ],
            options={
                'unique_together': {('product', 'location')},
            },
        ),
    ]
