# Generated by Django 3.0.3 on 2020-02-20 01:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProductTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_tree', to='Suppliers.SupplierLocation')),
            ],
        ),
    ]
