# Generated by Django 3.0.3 on 2020-03-03 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Addresses', '0002_address_demo'),
        ('Suppliers', '0002_supplierproducttree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierlocation',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Addresses.Address'),
        ),
    ]
