# Generated by Django 3.0.3 on 2020-03-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suppliers', '0003_auto_20200303_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierlocation',
            name='hash_value',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
