# Generated by Django 2.2.1 on 2019-08-25 23:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProductCollections', '0001_initial'),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_available_in_store', models.IntegerField(default=0, null=True)),
                ('units_per_order', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('product_bb_sku', models.CharField(max_length=60)),
                ('publish_in_store_availability', models.BooleanField(default=True)),
                ('publish_in_store_price', models.BooleanField(default=False)),
                ('publish_online_price', models.BooleanField(default=False)),
                ('in_store_ppu', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('online_ppu', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('lead_time_ts', models.DurationField(blank=True, default=datetime.timedelta(0), null=True)),
                ('offer_installation', models.BooleanField(default=False)),
                ('banner_item', models.BooleanField(default=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priced', to='Products.Product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='UserProductCollections.RetailerLocation')),
            ],
            options={
                'unique_together': {('product', 'retailer')},
            },
        ),
        migrations.CreateModel(
            name='ProjectProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_products', to='Products.Product')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='UserProductCollections.BaseProject')),
            ],
            options={
                'unique_together': {('product', 'project')},
            },
        ),
    ]
