# Generated by Django 3.0 on 2020-01-02 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProducts', '0001_initial'),
    ]

    database_operations = [
        migrations.AlterModelTable('ProjectProduct', 'projects__projectproduct'),
        migrations.AlterModelTable('RetailerProduct', 'retailers__retailerproduct')
        ]

    state_operations = [
        migrations.DeleteModel('ProjectProduct'),
        migrations.DeleteModel('RetailerProduct'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        )
    ]
