# Generated by Django 3.0 on 2020-01-02 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profiles', '0001_initial'),
        ('Addresses', '0001_initial'),
        ('Groups', '0001_initial'),
        ('Products', '0001_initial'),
        ('Retailers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project-images/')),
                ('template', models.BooleanField(default=False)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='Addresses.Address')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerCollaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=80, null=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='Profiles.ConsumerProfile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='Projects.BaseProject')),
            ],
        ),
        migrations.CreateModel(
            name='ProCollaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=80, null=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='Groups.ProCompany')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborations', to='Profiles.ProEmployeeProfile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_collaborators', to='Projects.BaseProject')),
            ],
            options={
                'unique_together': {('project', 'collaborator')},
            },
        ),
        migrations.CreateModel(
            name='ProductAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('quantity_needed', models.IntegerField()),
                ('procured', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='Products.Product')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_assignments', to='Projects.BaseProject')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='Retailers.RetailerLocation')),
                ('supplier_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='Retailers.RetailerProduct')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('predecessor_type', models.CharField(choices=[('FTS', 'Finish to Start'), ('STS', 'Start to Start'), ('FTF', 'Finish to Finish')], default='FTS', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('progress', models.IntegerField(null=True)),
                ('level', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Projects.ProjectTask')),
                ('predecessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependants', to='Projects.ProjectTask')),
                ('pro_collaborator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.ProCollaborator')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='Projects.ProductAssignment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Projects.BaseProject')),
                ('user_collaborator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.ConsumerCollaborator')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_products', to='Products.Product')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Projects.BaseProject')),
            ],
            options={
                'unique_together': {('product', 'project')},
            },
        ),
        migrations.CreateModel(
            name='ProProject',
            fields=[
                ('baseproject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Projects.BaseProject')),
                ('nickname', models.CharField(max_length=60)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Groups.ProCompany')),
            ],
            options={
                'unique_together': {('nickname', 'owner')},
            },
            bases=('Projects.baseproject',),
        ),
        migrations.CreateModel(
            name='ConsumerProject',
            fields=[
                ('baseproject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Projects.BaseProject')),
                ('nickname', models.CharField(max_length=60)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Profiles.ConsumerProfile')),
            ],
            options={
                'unique_together': {('nickname', 'owner')},
            },
            bases=('Projects.baseproject',),
        ),
    ]
