# Generated by Django 3.0.3 on 2020-02-12 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Suppliers', '0001_initial'),
        ('Addresses', '0001_initial'),
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project-images/')),
                ('template', models.BooleanField(default=False)),
                ('nickname', models.CharField(max_length=60)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='Addresses.Address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Profiles.ConsumerProfile')),
            ],
            options={
                'unique_together': {('nickname', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('predecessor_type', models.CharField(choices=[('FTS', 'Finish to Start'), ('STS', 'Start to Start'), ('FTF', 'Finish to Finish')], default='FTS', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('progress', models.IntegerField(null=True)),
                ('level', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Projects.ProjectTask')),
                ('predecessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependants', to='Projects.ProjectTask')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.IntegerField(blank=True, null=True)),
                ('procured', models.BooleanField(default=False)),
                ('linked_tasks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Projects.ProjectTask')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='Profiles.LibraryProduct')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Projects.Project')),
                ('supplier_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='Suppliers.SupplierProduct')),
            ],
        ),
        migrations.CreateModel(
            name='AddtionalProjectCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('label', models.CharField(max_length=60)),
                ('notes', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_costs', to='Projects.Project')),
            ],
        ),
    ]
