# Generated by Django 3.0 on 2020-01-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='quantity_needed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
