# Generated by Django 3.0 on 2020-01-03 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_auto_20200103_0752'),
        ('Groups', '0001_initial'),
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddtionalProjectCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('label', models.CharField(max_length=60)),
                ('notes', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additonal_costs', to='Projects.BaseProject')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('accepted', models.BooleanField(default=False)),
                ('files', models.FileField(null=True, upload_to='bids/')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profiles.ProEmployeeProfile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='bids', to='Groups.ProCompany')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='Projects.BaseProject')),
            ],
        ),
        migrations.CreateModel(
            name='BidInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='bid_invites', to='Groups.ProCompany')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_invites', to='Projects.BaseProject')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='procollaborator',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='procollaborator',
            name='collaborator',
        ),
        migrations.RemoveField(
            model_name='procollaborator',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='procollaborator',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='pro_collaborator',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='user_collaborator',
        ),
        migrations.DeleteModel(
            name='ConsumerCollaborator',
        ),
        migrations.DeleteModel(
            name='ProCollaborator',
        ),
        migrations.AddField(
            model_name='bidinvitation',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_invites', to='Projects.ProjectTask'),
        ),
        migrations.AddField(
            model_name='bid',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='Projects.ProjectTask'),
        ),
    ]
