# Generated by Django 3.0.2 on 2020-02-06 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LibraryProduct',
        ),
    ]
