# Generated by Django 3.0.2 on 2020-02-06 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0023_product_category'),
        ('Suppliers', '0001_initial'),
        ('Projects', '0002_delete_libraryproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttask',
            name='product',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='retailer_product',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='selected_retailer',
        ),
        migrations.CreateModel(
            name='ProjectProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_tasks', models.ManyToManyField(to='Projects.ProjectTask')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='Products.Product')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Projects.Project')),
                ('retailer_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='Suppliers.SupplierProduct')),
            ],
        ),
    ]
