# Generated by Django 3.0 on 2020-01-09 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Retailers', '0001_initial'),
        ('Projects', '0002_auto_20200108_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='retailer_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='Retailers.RetailerProduct'),
        ),
    ]
