# Generated by Django 3.0 on 2020-01-08 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
        ('Groups', '0001_initial'),
        ('Projects', '0002_auto_20200108_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Groups.BaseGroup'),
        ),
        migrations.CreateModel(
            name='LibraryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Groups.BaseGroup')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_products', to='Products.Product')),
            ],
            options={
                'unique_together': {('product', 'owner')},
            },
        ),
    ]
