# Generated by Django 3.0.3 on 2020-03-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20200310_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
