# Generated by Django 3.0 on 2020-01-03 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20200103_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtionalprojectcosts',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_costs', to='Projects.BaseProject'),
        ),
    ]
