# Generated by Django 3.0.3 on 2020-03-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='finish',
            field=models.DateTimeField(null=True),
        ),
    ]
