# Generated by Django 3.0.2 on 2020-02-06 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0004_libraryproduct'),
        ('Projects', '0003_auto_20200206_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttask',
            name='procured',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='quantity_needed',
        ),
        migrations.AddField(
            model_name='projectproduct',
            name='procured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectproduct',
            name='quantity_needed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='Profiles.LibraryProduct'),
        ),
    ]
