# Generated by Django 3.0.3 on 2020-03-12 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_projecttask_finish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttask',
            old_name='finish',
            new_name='estimated_finish',
        ),
    ]
