# Generated by Django 3.0.2 on 2020-02-06 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0004_libraryproduct'),
        ('Projects', '0004_auto_20200206_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='Profiles.LibraryProduct'),
        ),
    ]
