# Generated by Django 3.0.3 on 2020-03-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_auto_20200312_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='dependency_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
