# Generated by Django 3.0.2 on 2020-02-06 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_auto_20200206_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectproduct',
            name='linked_tasks',
        ),
        migrations.AddField(
            model_name='projectproduct',
            name='linked_tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.ProjectTask'),
        ),
    ]
