# Generated by Django 3.0.2 on 2020-02-06 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_auto_20200206_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproduct',
            name='linked_tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Projects.ProjectTask'),
        ),
    ]
