# Generated by Django 3.0.3 on 2020-03-18 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Suppliers', '0004_supplierlocation_hash_value'),
        ('Projects', '0006_projecttask_dependency_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproduct',
            name='linked_tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Projects.ProjectTask'),
        ),
        migrations.AlterField(
            model_name='projectproduct',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Projects.Project'),
        ),
        migrations.AlterField(
            model_name='projectproduct',
            name='supplier_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Suppliers.SupplierProduct'),
        ),
    ]
