# Generated by Django 3.0.2 on 2020-02-07 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_auto_20200206_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectproduct',
            old_name='retailer_product',
            new_name='supplier_product',
        ),
    ]
