# Generated by Django 3.0.3 on 2020-03-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_auto_20200318_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='estimated_start',
            field=models.DateTimeField(null=True),
        ),
    ]
