
emails = [
    'jondoe@hotgmail.com',
    'janedoes@hotgmail.com',
    'burtchrysler@hotgmail.com',
    'seguras@hotgmail.com',
    'custus@hotgmail.com',
    'walden@hotgmail.com'
]

phone_number = '4044335741'

addresses = [
    ['1211 Thornton Rd', 'Lithia Springs', 'GA', '30122'],
    ['1477 Kilchis Falls Way', 'Braselton', 'GA', '30517'],
    ['958 Thomas Powers Rd', 'Newnan', 'GA', '30263'],
    ['577 Martinique Cir', 'Redding', 'CA', '96003'],
    ['9856 W Tompkins Ave', 'Las Vegas', 'NV', '89147'],
    ['236 Union St', 'Spartanburg', 'SC', '29302']
    ]

company_names = [
    'rustic interiors _test',
    'antique finishes _test',
    'southern materials _test',
    'spartan tile _test',
    'elegant flooring _test',
    'crickets woodshop _test'
]

MODS = [
    [
        'Armstrong',
        'ScraperFinishSurface',
        'residential_engineeredtile',
        'https://www.armstrongflooring.com/residential/en-us/engineered-tile/_jcr_content.browseresults.json?pageSize=139&currPageIndex=1'
    ],
    [
        'Armstrong',
        'ScraperFinishSurface',
        'residential_hardwood',
        'https://www.armstrongflooring.com/residential/en-us/hardwood-flooring/_jcr_content.browseresults.json?pageSize=386&currPageIndex=1'
    ],
    [
        'Armstrong',
        'ScraperFinishSurface',
        'residential_laminate',
        'https://www.armstrongflooring.com/residential/en-us/laminate-flooring/_jcr_content.browseresults.json?pageSize=93&currPageIndex=1'
    ],
    [
        'Armstrong',
        'ScraperFinishSurface',
        'residential_lvt',
        'https://www.armstrongflooring.com/residential/en-us/vinyl-flooring/luxury-vinyl-tile/_jcr_content.browseresults.json?pageSize=111&currPageIndex=1'
    ],
    [
        'Armstrong',
        'ScraperFinishSurface',
        'residential_rigidcore',
        'https://www.armstrongflooring.com/residential/en-us/rigid-core/_jcr_content.browseresults.json?pageSize=78&currPageIndex=1'
    ],
    [
        'Armstrong',
        'ScraperFinishSurface',
        'residential_vinylsheet',
        'https://www.armstrongflooring.com/residential/en-us/vinyl-flooring/vinyl-sheet/_jcr_content.browseresults.json?pageSize=252&currPageIndex=1'
    ],
    [
        'Armstrong',
        'ScraperFinishSurface',
        'residential_vinyltile',
        'https://www.armstrongflooring.com/residential/en-us/vinyl-flooring/vinyl-tile/_jcr_content.browseresults.json?pageSize=26&currPageIndex=1'
    ],
    [
        'Armstrong',
        'ScraperFinishSurface',
        'commercial_hardwood',
        'https://www.armstrongflooring.com/commercial/en-us/products/commercial-hardwood/browse/_jcr_content.browseresults.json?category=hw&pageSize=60&currPageIndex=1'
    ],
    [
        'Armstrong',
        'ScraperFinishSurface',
        'commercial_heterovinyl',
        'https://www.armstrongflooring.com/commercial/en-us/products/het/browse/_jcr_content.browseresults.json?category=het&pageSize=167&currPageIndex=1'
    ],
    [
        'Armstrong',
        'ScraperFinishSurface',
        'commercial_homovinyl',
        'https://www.armstrongflooring.com/commercial/en-us/products/hom/browse/_jcr_content.browseresults.json?category=hom&pageSize=89&currPageIndex=1'
    ],
    [
        'Armstrong',
        'ScraperFinishSurface',
        'commercial_laminate',
        'https://www.armstrongflooring.com/commercial/en-us/products/commercial-laminate/browse/_jcr_content.browseresults.json?category=lam&pageSize=27&currPageIndex=1'
    ],
    [
        'Armstrong',
        'ScraperFinishSurface',
        'commercial_linoleum',
        'https://www.armstrongflooring.com/commercial/en-us/products/linoleum/browse/_jcr_content.browseresults.json?category=lin&pageSize=92&currPageIndex=1'
    ],
    [
        'Armstrong',
        'ScraperFinishSurface',
        'commercial_luxuryflooring',
        'https://www.armstrongflooring.com/commercial/en-us/products/lvt-luxury-flooring/browse/_jcr_content.browseresults.json?category=lvt&pageSize=320&currPageIndex=1'
    ],
    [
        'Crossville',
        'ScraperFinishSurface',
        'tiles',
        'https://www.crossvilleinc.com/api/Products'
    ],
    [
        'Shaw',
        'ScraperFinishSurface',
        'laminate',
        '''https://shawfloors.com/api/odata/Laminates?
            $top=1000
            &$select=
            UniqueId,
            SellingStyleNbr,
            SellingColorNbr,
            PlankWidth,
            InstallationType,
            PlankLength,
            Thickness,
            Warranty,
            EdgeType,
            SellingStyleName,
            SellingColorName,
            StaticRoomFlag,
            Vignette,
            ColorCount,
            MSRPRange,
            HasSwatchImage,
            SampleCount,
            IsMadeInUsa,
            CollectionDesc
            &$filter=(IsBaselineData%20eq%20false)%20and%20(IsDropped%20eq%20false)%20and%20(ColorCount%20gt%200)%20and%20(ProductGroupPermanentName%20eq%20%27shawfloors%27)%20and%20(HasMainImage%20eq%20true)%20and%20(ProductGroupShowOnBrowseCat%20eq%20true)%20and%20(HasMainImage%20eq%20true)%20and%20(StaticRoomFlag%20eq%20true%20or%20HasRenderImage%20eq%20true)
            &$orderby=StyleSequence,UniqueId
            &$count=true'''
    ],
    [
        'Shaw',
        'ScraperFinishSurface',
        'tile-and-stone',
        '''https://shawfloors.com/api/odata/Ceramics?
            $top=1000
            &$select=
            UniqueId,
            SellingStyleNbr,
            SellingColorNbr,
            SellingStyleName,
            SellingColorName,
            StaticRoomFlag,
            Thickness,
            Thickness,
            WIDTH,
            LengthDimension,            
            InstallOnFloorsAndWalls,
            InstallOnFloors,
            InstallOnWalls,
            InstallOnExterior,
            InstallOnCountertops,
            Look,
            CeramicConstruction,
            SurfaceTexture,
            SurfaceFinish,
            WetCof,
            Vignette,
            ColorCount,
            MSRPRange,
            SampleCount,
            MadeInUSA
            &$filter=(IsBaselineData%20eq%20false)%20and%20(IsDropped%20eq%20false)%20and%20(ColorCount%20gt%200)%20and%20(ProductGroupPermanentName%20eq%20%27shawfloors%27)%20and%20(HasMainImage%20eq%20true)%20and%20(ProductGroupShowOnBrowseCat%20eq%20true)%20and%20(HasMainImage%20eq%20true)%20and%20(StaticRoomFlag%20eq%201%20or%20HasRenderImage%20eq%20true)
            &$orderby=StyleSequence,UniqueId
            &$count=true'''
    ],
    [
        'Shaw',
        'ScraperFinishSurface',
        'hardwood',
        '''https://shawfloors.com/api/odata/Hardwoods?
            $top=81&$skip=0
            &$select=
            UniqueId,
            SellingStyleNbr,
            SellingColorNbr,
            SellingStyleName,
            SellingColorName,
            StaticRoomFlag,
            Vignette,
            ColorCount,
            MSRPRange,
            HasSwatchImage,
            SampleCount,
            IsMadeInUsa,
            InstallationType,
            PlankWidth,
            PlankLength,
            Thickness,
            EdgeType,
            GlossLevel,
            ColorVariationRatingShortDesc,
            Species,
            Warranty,
            Construction,
            CollectionDesc
            &$orderby=StyleSequence,UniqueId
            &$filter=(IsBaselineData%20eq%20false)%20and%20(IsDropped%20eq%20false)%20and%20(ColorCount%20gt%200)%20and%20(ProductGroupPermanentName%20eq%20%27shawfloors%27)%20and%20(HasMainImage%20eq%20true)%20and%20(ProductGroupShowOnBrowseCat%20eq%20true)%20and%20(HasMainImage%20eq%20true)%20and%20(StaticRoomFlag%20eq%20true%20or%20HasRenderImage%20eq%20true)
            &$count=true'''
    ],
    [
        'Shaw',
        'ScraperFinishSurface',
        'resilient',
        '''https://shawfloors.com/api/odata/resilient?
            $top=81&$skip=0
            &$select=
            UniqueId,
            SellingStyleNbr,
            SellingColorNbr,
            SellingStyleName,
            SellingColorName,
            StaticRoomFlag,
            Vignette,
            ColorCount,
            MSRPRange,
            HasSwatchImage,
            SampleCount,
            IsMadeInUsa,
            SizeWidth,
            SizeLength,
            Thickness,
            Finish,
            Warranty,
            LightComWarranty,
            ProductCatDesc,
            Look,
            SurfaceTexture,
            GlossLevel,
            LightComWarranty,
            InstallationMethodDesc,
            CollectionDesc
            &$orderby=StyleSequence,UniqueId
            &$filter=(IsBaselineData%20eq%20false)%20and%20(IsDropped%20eq%20false)%20and%20(ColorCount%20gt%200)%20and%20(ProductGroupPermanentName%20eq%20%27shawfloors%27)%20and%20(HasMainImage%20eq%20true)%20and%20(ProductGroupShowOnBrowseCat%20eq%20true)%20and%20(HasMainImage%20eq%20true)%20and%20(StaticRoomFlag%20eq%20true%20or%20HasRenderImage%20eq%20true)
            &$count=true'''
    ],
    [
        'FloridaTile',
        'ScraperFinishSurface',
        'tile',
        ''
    ],
    [
        'Mohawk',
        'ScraperFinishSurface',
        'hardwood',
        'https://www.mohawkflooring.com/api/products/styles'
    ],
    [
        'Mohawk',
        'ScraperFinishSurface',
        'tile',
        'https://www.mohawkflooring.com/api/products/styles'
    ],
    [
        'Mohawk',
        'ScraperFinishSurface',
        'vinyl',
        'https://www.mohawkflooring.com/api/products/styles'
    ]
]
