# Generated by Django 2.2.1 on 2019-08-30 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperFinishSurface',
            fields=[
                ('scraperbaseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Scraper.ScraperBaseProduct')),
                ('material', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_material', models.CharField(blank=True, max_length=200, null=True)),
                ('finish', models.CharField(blank=True, max_length=200, null=True)),
                ('look', models.CharField(blank=True, max_length=200, null=True)),
                ('surface_coating', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('shade_variation', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('shape', models.CharField(blank=True, max_length=60, null=True)),
                ('actual_color', models.CharField(blank=True, max_length=50, null=True)),
                ('label_color', models.CharField(blank=True, max_length=50, null=True)),
                ('edge', models.CharField(blank=True, max_length=200, null=True)),
                ('end', models.CharField(blank=True, max_length=200, null=True)),
                ('walls', models.BooleanField(default=False)),
                ('countertops', models.BooleanField(default=False)),
                ('floors', models.BooleanField(default=False)),
                ('cabinet_fronts', models.BooleanField(default=False)),
                ('shower_floors', models.BooleanField(default=False)),
                ('shower_walls', models.BooleanField(default=False)),
                ('exterior_walls', models.BooleanField(default=False)),
                ('exterior_floors', models.BooleanField(default=False)),
                ('covered_walls', models.BooleanField(default=False)),
                ('covered_floors', models.BooleanField(default=False)),
                ('pool_linings', models.BooleanField(default=False)),
                ('bullnose', models.BooleanField(default=False)),
                ('covebase', models.BooleanField(default=False)),
                ('corner_covebase', models.BooleanField(default=False)),
                ('thickness', models.CharField(blank=True, max_length=50, null=True)),
                ('width', models.CharField(blank=True, max_length=50, null=True)),
                ('length', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=30, null=True)),
                ('lrv', models.CharField(blank=True, max_length=60, null=True)),
                ('cof', models.CharField(blank=True, max_length=60, null=True)),
                ('install_type', models.CharField(blank=True, max_length=100, null=True)),
                ('sqft_per_carton', models.CharField(blank=True, max_length=70, null=True)),
                ('slip_resistant', models.BooleanField(default=False)),
                ('web_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
            bases=('Scraper.scraperbaseproduct',),
        ),
    ]
