# Generated by Django 3.0.3 on 2020-02-13 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=200, null=True)),
                ('session_id', models.CharField(max_length=120, null=True)),
                ('path', models.CharField(max_length=500, null=True)),
                ('base_path', models.CharField(max_length=200, null=True)),
                ('path_params', models.CharField(max_length=300, null=True)),
                ('cleaned', models.BooleanField(default=False)),
                ('best_location', models.BooleanField(default=False)),
                ('product_detail_pk', models.CharField(max_length=120, null=True)),
                ('supplier_pk', models.IntegerField(null=True)),
                ('pro_company_pk', models.IntegerField(null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Addresses.Coordinate')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewRecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
