# Generated by Django 2.2.1 on 2019-09-08 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Addresses', '0001_initial'),
        ('ProductFilter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfoViewRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlansRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded', models.DateTimeField(auto_now_add=True)),
                ('consumer_plans', models.IntegerField(default=0)),
                ('retailer_plans', models.IntegerField(default=0)),
                ('pro_plans', models.IntegerField(default=0)),
                ('no_plan_consumers', models.IntegerField(default=0)),
                ('no_plan_retailers', models.IntegerField(default=0)),
                ('no_plan_pros', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductViewRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=200, null=True)),
                ('floating_fields', models.CharField(max_length=200, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Addresses.Coordinate')),
                ('query_index', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record', to='ProductFilter.QueryIndex')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
