# Generated by Django 3.0.3 on 2020-03-07 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewrecord',
            name='location',
        ),
    ]
