# Generated by Django 3.0.3 on 2020-03-07 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Addresses', '0002_address_demo'),
        ('Analytics', '0002_remove_viewrecord_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewrecord',
            name='best_location',
        ),
        migrations.RemoveField(
            model_name='viewrecord',
            name='cleaned',
        ),
        migrations.RemoveField(
            model_name='viewrecord',
            name='path',
        ),
        migrations.RemoveField(
            model_name='viewrecord',
            name='pro_company_pk',
        ),
        migrations.RemoveField(
            model_name='viewrecord',
            name='product_detail_pk',
        ),
        migrations.RemoveField(
            model_name='viewrecord',
            name='supplier_pk',
        ),
        migrations.AddField(
            model_name='viewrecord',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Addresses.Coordinate'),
        ),
    ]
