# Generated by Django 3.0 on 2019-12-12 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Addresses', '0002_auto_20190917_0224'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Analytics', '0002_productviewrecord_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=200, null=True)),
                ('path', models.CharField(max_length=200, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Addresses.Coordinate')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewRecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CompanyInfoViewRecord',
        ),
        migrations.DeleteModel(
            name='ProductViewRecord',
        ),
    ]
