# Generated by Django 3.0.3 on 2020-03-07 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Suppliers', '0004_supplierlocation_hash_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Addresses', '0002_address_demo'),
        ('Products', '0005_auto_20200227_0443'),
        ('Analytics', '0003_auto_20200307_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=200, null=True)),
                ('session_id', models.CharField(max_length=120, null=True)),
                ('base_path', models.CharField(max_length=200, null=True)),
                ('path_params', models.CharField(max_length=300, null=True)),
                ('view', models.CharField(max_length=60)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Addresses.Coordinate')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductDetailRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=200, null=True)),
                ('session_id', models.CharField(max_length=120, null=True)),
                ('base_path', models.CharField(max_length=200, null=True)),
                ('path_params', models.CharField(max_length=300, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Addresses.Coordinate')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierProductListRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=200, null=True)),
                ('session_id', models.CharField(max_length=120, null=True)),
                ('base_path', models.CharField(max_length=200, null=True)),
                ('path_params', models.CharField(max_length=300, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Addresses.Coordinate')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Suppliers.SupplierLocation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ViewRecord',
        ),
    ]
