# Generated by Django 3.0 on 2019-12-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0003_auto_20191212_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewrecord',
            name='product_detail_pk',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='viewrecord',
            name='supplier_pk',
            field=models.IntegerField(null=True),
        ),
    ]
