# Generated by Django 3.0 on 2019-12-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0004_auto_20191212_0156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlansRecord',
        ),
        migrations.AddField(
            model_name='viewrecord',
            name='base_path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='viewrecord',
            name='cleaned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='viewrecord',
            name='path_params',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='viewrecord',
            name='session_id',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='viewrecord',
            name='path',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
