# Generated by Django 3.0.3 on 2020-03-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0004_auto_20200307_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericrecord',
            name='recorded',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='productdetailrecord',
            name='recorded',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='supplierproductlistrecord',
            name='recorded',
            field=models.DateTimeField(null=True),
        ),
    ]
