# Generated by Django 3.0.3 on 2020-08-30 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Suppliers', '0004_supplierlocation_hash_value'),
        ('Analytics', '0005_auto_20200323_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproductlistrecord',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='Suppliers.SupplierLocation'),
        ),
    ]
