# Generated by Django 3.0 on 2019-12-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0005_auto_20191212_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewrecord',
            name='pro_company_pk',
            field=models.IntegerField(null=True),
        ),
    ]
