# Generated by Django 3.0 on 2019-12-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0006_viewrecord_pro_company_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewrecord',
            name='best_location',
            field=models.BooleanField(default=False),
        ),
    ]
