# Generated by Django 2.0.6 on 2019-05-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('duration', models.DurationField()),
                ('billing_recurrence', models.DurationField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('project_threshold', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('duration', models.DurationField()),
                ('billing_recurrence', models.DurationField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('location_threshold', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
