# Generated by Django 3.0 on 2020-01-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('duration', models.DurationField()),
                ('billing_recurrence', models.DurationField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('location_threshold', models.IntegerField(default=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('duration', models.DurationField()),
                ('billing_recurrence', models.DurationField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('location_threshold', models.IntegerField(default=2)),
                ('employee_limit', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RetailerPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('duration', models.DurationField()),
                ('billing_recurrence', models.DurationField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('location_threshold', models.IntegerField(default=2)),
                ('employee_limit', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
