# Generated by Django 2.0.6 on 2019-02-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerplan',
            name='project_threshold',
            field=models.IntegerField(default=2),
        ),
    ]
