# Generated by Django 2.2.1 on 2019-09-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proplan',
            name='employee_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='retailerplan',
            name='employee_limit',
            field=models.IntegerField(default=1),
        ),
    ]
