# Generated by Django 2.0.6 on 2018-06-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='name',
            field=models.CharField(default='Library', max_length=50),
        ),
        migrations.AlterField(
            model_name='library',
            name='materials',
            field=models.ManyToManyField(blank=True, null=True, to='Products.Product'),
        ),
    ]
