# Generated by Django 2.0.6 on 2018-07-20 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0001_initial'),
        ('Libraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlibrary',
            name='products',
            field=models.ManyToManyField(related_name='users_libraries', to='Products.Product'),
        ),
        migrations.AddField(
            model_name='supplierlibrary',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_library', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierlibrary',
            name='products',
            field=models.ManyToManyField(related_name='suppliers_libraries', to='Products.SupplierProduct'),
        ),
    ]
