# Generated by Django 2.0.6 on 2018-07-19 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Libraries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierlibrary',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_library', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlibrary',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_library', to=settings.AUTH_USER_MODEL),
        ),
    ]
