# Generated by Django 2.0.6 on 2018-06-25 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20180625_1121'),
        ('Libraries', '0002_auto_20180624_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierLibrary',
            fields=[
                ('library_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Libraries.Library')),
            ],
            bases=('Libraries.library',),
        ),
        migrations.CreateModel(
            name='UserLibrary',
            fields=[
                ('library_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Libraries.Library')),
                ('products', models.ManyToManyField(to='Products.Product')),
            ],
            bases=('Libraries.library',),
        ),
        migrations.AlterUniqueTogether(
            name='supplierproduct',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='library',
            name='materials',
        ),
        migrations.DeleteModel(
            name='SupplierProduct',
        ),
        migrations.AddField(
            model_name='supplierlibrary',
            name='products',
            field=models.ManyToManyField(to='Products.SupplierProduct'),
        ),
    ]
