# Generated by Django 2.0.6 on 2018-07-20 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Libraries', '0002_auto_20180719_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierlibrary',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_library', to='Profiles.CompanyShippingLocation'),
        ),
    ]
