# Generated by Django 3.0.3 on 2020-02-13 22:00

from decimal import Decimal
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFacet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('attribute', models.CharField(blank=True, max_length=60, null=True)),
                ('attribute_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=60, null=True), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='FacetOthersCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueryIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_dict', models.CharField(max_length=1000)),
                ('query_path', models.CharField(max_length=500)),
                ('dirty', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('last_retrieved', models.DateTimeField(auto_now_add=True, null=True)),
                ('times_accessed', models.PositiveIntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoolFacet',
            fields=[
                ('basefacet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ProductFilter.BaseFacet')),
            ],
            bases=('ProductFilter.basefacet',),
        ),
        migrations.CreateModel(
            name='DynamicDecimalFacet',
            fields=[
                ('basefacet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ProductFilter.BaseFacet')),
                ('tick', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=7)),
            ],
            options={
                'abstract': False,
            },
            bases=('ProductFilter.basefacet',),
        ),
        migrations.CreateModel(
            name='DynamicRangeFacet',
            fields=[
                ('basefacet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ProductFilter.BaseFacet')),
                ('tick', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=7)),
            ],
            options={
                'abstract': False,
            },
            bases=('ProductFilter.basefacet',),
        ),
        migrations.CreateModel(
            name='RadiusFacet',
            fields=[
                ('basefacet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ProductFilter.BaseFacet')),
            ],
            bases=('ProductFilter.basefacet',),
        ),
        migrations.CreateModel(
            name='StaticDecimalFacet',
            fields=[
                ('basefacet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ProductFilter.BaseFacet')),
                ('tick', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=7)),
                ('abs_min', models.DecimalField(decimal_places=2, max_digits=8)),
                ('abs_max', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'abstract': False,
            },
            bases=('ProductFilter.basefacet',),
        ),
        migrations.CreateModel(
            name='StaticRangeFacet',
            fields=[
                ('basefacet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ProductFilter.BaseFacet')),
                ('tick', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=7)),
                ('abs_min', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=8), size=None)),
                ('abs_max', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=8), size=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('ProductFilter.basefacet',),
        ),
    ]
