# Generated by Django 3.0.3 on 2020-02-13 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ProductFilter', '0001_initial'),
        ('Suppliers', '0001_initial'),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryindex',
            name='products',
            field=models.ManyToManyField(related_name='query_indexes', to='Products.Product'),
        ),
        migrations.AddField(
            model_name='queryindex',
            name='retailer_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qis', to='Suppliers.SupplierLocation'),
        ),
        migrations.AddField(
            model_name='facetotherscollection',
            name='facet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProductFilter.BaseFacet'),
        ),
        migrations.AddField(
            model_name='facetotherscollection',
            name='products',
            field=models.ManyToManyField(related_name='facet_collections', to='Products.Product'),
        ),
        migrations.AddField(
            model_name='facetotherscollection',
            name='query_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='others', to='ProductFilter.QueryIndex'),
        ),
        migrations.AddField(
            model_name='basefacet',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'SpecializedProducts'), models.Q(('app_label', 'Products'), ('model', 'Product')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterUniqueTogether(
            name='queryindex',
            unique_together={('query_dict', 'query_path')},
        ),
        migrations.AlterUniqueTogether(
            name='facetotherscollection',
            unique_together={('query_index', 'facet')},
        ),
        migrations.AlterUniqueTogether(
            name='basefacet',
            unique_together={('attribute', 'content_type', 'attribute_list')},
        ),
    ]
