# Generated by Django 3.0.3 on 2020-02-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0005_auto_20200214_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticrangefacet',
            name='abs_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='staticrangefacet',
            name='abs_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='staticdecimalfacet',
            name='abs_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='staticdecimalfacet',
            name='abs_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
