# Generated by Django 3.0.3 on 2020-02-17 16:22

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ProductFilter', '0007_multifacet'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='basefacet',
            managers=[
                ('subclasses', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='boolfacet',
            managers=[
                ('subclasses', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='dynamicdecimalfacet',
            managers=[
                ('subclasses', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='dynamicrangefacet',
            managers=[
                ('subclasses', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='multifacet',
            managers=[
                ('subclasses', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='radiusfacet',
            managers=[
                ('subclasses', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='staticdecimalfacet',
            managers=[
                ('subclasses', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='staticrangefacet',
            managers=[
                ('subclasses', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='basefacet',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'Products'), ('app_label', 'SpecializedProducts'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
