# Generated by Django 3.0.3 on 2020-02-17 23:18

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0008_auto_20200217_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonNullFacet',
            fields=[
                ('basefacet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ProductFilter.BaseFacet')),
            ],
            bases=('ProductFilter.basefacet',),
            managers=[
                ('subclasses', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='multifacet',
            name='allow_multiple',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='multifacet',
            name='widget',
            field=models.CharField(default='checkbox', max_length=30),
        ),
    ]
