# Generated by Django 3.0.3 on 2020-02-17 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0009_auto_20200217_2318'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='basefacet',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='boolfacet',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='dynamicdecimalfacet',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='dynamicrangefacet',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='multifacet',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='nonnullfacet',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='radiusfacet',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='staticdecimalfacet',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='staticrangefacet',
            managers=[
            ],
        ),
    ]
