# Generated by Django 3.0.3 on 2020-02-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0010_auto_20200217_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicdecimalfacet',
            name='basefacet_ptr',
        ),
        migrations.RemoveField(
            model_name='dynamicrangefacet',
            name='basefacet_ptr',
        ),
        migrations.RemoveField(
            model_name='multifacet',
            name='basefacet_ptr',
        ),
        migrations.RemoveField(
            model_name='nonnullfacet',
            name='basefacet_ptr',
        ),
        migrations.RemoveField(
            model_name='radiusfacet',
            name='basefacet_ptr',
        ),
        migrations.RemoveField(
            model_name='staticdecimalfacet',
            name='basefacet_ptr',
        ),
        migrations.RemoveField(
            model_name='staticrangefacet',
            name='basefacet_ptr',
        ),
        migrations.AddField(
            model_name='basefacet',
            name='abs_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='basefacet',
            name='abs_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='basefacet',
            name='allow_multiple',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='basefacet',
            name='dynamic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basefacet',
            name='editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basefacet',
            name='field_type',
            field=models.CharField(default='CharField', max_length=70),
        ),
        migrations.AddField(
            model_name='basefacet',
            name='widget',
            field=models.CharField(default='checkbox', max_length=30),
        ),
        migrations.DeleteModel(
            name='BoolFacet',
        ),
        migrations.DeleteModel(
            name='DynamicDecimalFacet',
        ),
        migrations.DeleteModel(
            name='DynamicRangeFacet',
        ),
        migrations.DeleteModel(
            name='MultiFacet',
        ),
        migrations.DeleteModel(
            name='NonNullFacet',
        ),
        migrations.DeleteModel(
            name='RadiusFacet',
        ),
        migrations.DeleteModel(
            name='StaticDecimalFacet',
        ),
        migrations.DeleteModel(
            name='StaticRangeFacet',
        ),
    ]
