# Generated by Django 2.2.1 on 2019-05-15 06:05

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool_groups', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('key_field', models.CharField(blank=True, max_length=30, null=True)),
                ('color_field', models.CharField(blank=True, max_length=30, null=True)),
                ('independent_multichoice_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), blank=True, null=True, size=None)),
                ('independent_range_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), blank=True, null=True, size=None)),
                ('dependent_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), blank=True, null=True, size=None)),
                ('filter_dictionary', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueryIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_string', models.CharField(max_length=1000)),
                ('response', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('last_retrieved', models.DateTimeField(null=True)),
                ('times_accessed', models.PositiveIntegerField(default=1, null=True)),
                ('product_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_indexes', to='ProductFilter.ProductFilter')),
            ],
            options={
                'unique_together': {('query_string', 'product_filter')},
            },
        ),
    ]
