# Generated by Django 3.0 on 2020-01-08 05:18

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        ('Retailers', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool_groups', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('key_field', models.CharField(blank=True, max_length=30, null=True)),
                ('color_field', models.CharField(blank=True, max_length=30, null=True)),
                ('independent_multichoice_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), blank=True, null=True, size=None)),
                ('independent_range_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), blank=True, null=True, size=None)),
                ('dependent_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), blank=True, null=True, size=None)),
                ('filter_dictionary', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('sub_product_description', models.CharField(default='', max_length=500)),
                ('sub_product_image', models.FileField(blank=True, null=True, upload_to='misc/')),
                ('sub_product', models.OneToOneField(limit_choices_to={'app_label': 'SpecializedProducts'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='QueryIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_dict', models.CharField(max_length=1000)),
                ('query_path', models.CharField(max_length=500)),
                ('response', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('dirty', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('last_retrieved', models.DateTimeField(auto_now_add=True, null=True)),
                ('times_accessed', models.PositiveIntegerField(default=1, null=True)),
                ('product_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_indexes', to='ProductFilter.ProductFilter')),
                ('products', models.ManyToManyField(related_name='query_indexes', to='Products.Product')),
                ('retailer_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qis', to='Retailers.RetailerLocation')),
            ],
            options={
                'unique_together': {('query_dict', 'query_path')},
            },
        ),
        migrations.CreateModel(
            name='FacetOthersCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('facet_name', models.CharField(max_length=100)),
                ('products', models.ManyToManyField(related_name='facet_collections', to='Products.Product')),
                ('query_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductFilter.QueryIndex')),
            ],
            options={
                'unique_together': {('query_index', 'facet_name')},
            },
        ),
    ]
