# Generated by Django 2.2.1 on 2019-05-15 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ProductFilter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilter',
            name='sub_product',
            field=models.OneToOneField(limit_choices_to=models.Q(('app_label', 'FinishSurfaces'), ('model', 'finishsurface')), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
