# Generated by Django 3.0.2 on 2020-01-22 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facetotherscollection',
            name='query_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='others', to='ProductFilter.QueryIndex'),
        ),
    ]
