# Generated by Django 2.2.1 on 2019-08-16 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProductCollections', '0004_auto_20190804_1815'),
        ('ProductFilter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryindex',
            name='retailer_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qis', to='UserProductCollections.RetailerLocation'),
        ),
    ]
