# Generated by Django 2.2.1 on 2019-05-09 19:43

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilter',
            name='dependent_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), null=True, size=None),
        ),
        migrations.AddField(
            model_name='productfilter',
            name='key_field',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='productfilter',
            name='standalones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), null=True, size=None),
        ),
        migrations.CreateModel(
            name='QueryIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_string', models.CharField(max_length=1000)),
                ('response', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('last_retrieved', models.DateTimeField()),
                ('times_accessed', models.PositiveIntegerField()),
                ('product_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_indexes', to='ProductFilter.ProductFilter')),
            ],
            options={
                'unique_together': {('query_string', 'product_filter')},
            },
        ),
    ]
