# Generated by Django 2.2.1 on 2019-10-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilter',
            name='sub_product_description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='productfilter',
            name='sub_product_image',
            field=models.ImageField(blank=True, null=True, upload_to='misc/'),
        ),
    ]
