# Generated by Django 3.0.3 on 2020-02-18 05:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Suppliers', '0001_initial'),
        ('Products', '0003_initialproductvalues_valuecleaner'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFacet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('attribute', models.CharField(blank=True, max_length=60, null=True)),
                ('attribute_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=60, null=True), blank=True, null=True, size=None)),
                ('widget', models.CharField(default='checkbox', max_length=30)),
                ('dynamic', models.BooleanField(default=False)),
                ('editable', models.BooleanField(default=False)),
                ('field_type', models.CharField(default='CharField', max_length=70)),
                ('abs_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('abs_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('allow_multiple', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'Products'), ('app_label', 'SpecializedProducts'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'unique_together': {('attribute', 'content_type', 'attribute_list')},
            },
        ),
        migrations.CreateModel(
            name='QueryIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_dict', models.CharField(max_length=1000)),
                ('query_path', models.CharField(max_length=500)),
                ('dirty', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('last_retrieved', models.DateTimeField(auto_now_add=True, null=True)),
                ('times_accessed', models.PositiveIntegerField(default=1, null=True)),
                ('products', models.ManyToManyField(related_name='query_indexes', to='Products.Product')),
                ('retailer_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qis', to='Suppliers.SupplierLocation')),
            ],
            options={
                'unique_together': {('query_dict', 'query_path')},
            },
        ),
        migrations.CreateModel(
            name='FacetOthersCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('facet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProductFilter.BaseFacet')),
                ('products', models.ManyToManyField(related_name='facet_collections', to='Products.Product')),
                ('query_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='others', to='ProductFilter.QueryIndex')),
            ],
            options={
                'unique_together': {('query_index', 'facet')},
            },
        ),
    ]
