# Generated by Django 2.2.1 on 2019-05-09 22:12

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0002_auto_20190509_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilter',
            name='filter_dictionary',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productfilter',
            name='bool_groups',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productfilter',
            name='dependent_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='productfilter',
            name='standalones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), blank=True, null=True, size=None),
        ),
    ]
