# Generated by Django 2.2.1 on 2019-05-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20190516_2153'),
        ('ProductFilter', '0002_productfilter_sub_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryindex',
            name='products',
            field=models.ManyToManyField(related_name='query_indexes', to='Products.Product'),
        ),
    ]
