# Generated by Django 3.0.3 on 2020-02-20 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Suppliers', '0002_supplierproducttree'),
        ('ProductFilter', '0002'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='queryindex',
            unique_together={('query_dict', 'query_path', 'retailer_location')},
        ),
    ]
