# Generated by Django 3.0.3 on 2020-02-14 05:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0002_auto_20200213_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basefacet',
            name='attribute_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=60, null=True), blank=True, null=True, size=None),
        ),
    ]
