# Generated by Django 2.2.1 on 2019-10-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0002_auto_20191014_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfilter',
            name='sub_product_image',
            field=models.FileField(blank=True, null=True, upload_to='misc/'),
        ),
    ]
