# Generated by Django 2.2.1 on 2019-05-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0003_auto_20190509_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfilter',
            name='key_field',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
