# Generated by Django 3.0.3 on 2020-02-26 22:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0003_auto_20200220_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='basefacet',
            name='static_charfield_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=80, null=True), blank=True, null=True, size=None),
        ),
    ]
