# Generated by Django 2.2.1 on 2019-05-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0003_queryindex_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queryindex',
            old_name='query_string',
            new_name='query_dict',
        ),
        migrations.AddField(
            model_name='queryindex',
            name='query_path',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='queryindex',
            unique_together={('query_dict', 'query_path')},
        ),
    ]
