# Generated by Django 2.2.1 on 2019-05-10 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0004_auto_20190509_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfilter',
            old_name='standalones',
            new_name='standalone_text_fields',
        ),
    ]
