# Generated by Django 3.0.3 on 2020-02-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0004_basefacet_static_charfield_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoolFacet',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ProductFilter.basefacet',),
        ),
        migrations.CreateModel(
            name='CharFacet',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ProductFilter.basefacet',),
        ),
        migrations.CreateModel(
            name='ForeignFacet',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ProductFilter.basefacet',),
        ),
        migrations.CreateModel(
            name='LocationFacet',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ProductFilter.basefacet',),
        ),
        migrations.CreateModel(
            name='NumericFacet',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ProductFilter.basefacet',),
        ),
        migrations.AddField(
            model_name='basefacet',
            name='proxy_type',
            field=models.CharField(default='CharFacet', max_length=60),
        ),
    ]
