# Generated by Django 2.2.1 on 2019-05-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0004_auto_20190522_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryindex',
            name='last_retrieved',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
