# Generated by Django 3.0.3 on 2020-02-14 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0004_auto_20200214_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticrangefacet',
            name='abs_max',
        ),
        migrations.RemoveField(
            model_name='staticrangefacet',
            name='abs_min',
        ),
    ]
