# Generated by Django 2.2.1 on 2019-05-10 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0005_auto_20190510_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfilter',
            old_name='standalone_text_fields',
            new_name='independent_text_fields',
        ),
    ]
