# Generated by Django 3.0.3 on 2020-03-01 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0005_auto_20200228_0559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacetOthersCollection',
        ),
    ]
