# Generated by Django 2.2.1 on 2019-05-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0005_auto_20190523_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryindex',
            name='dirty',
            field=models.BooleanField(default=False),
        ),
    ]
