# Generated by Django 3.0.3 on 2020-03-06 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0006_delete_facetotherscollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTypeFacet',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ProductFilter.basefacet',),
        ),
    ]
