# Generated by Django 3.0.3 on 2020-02-14 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0006_auto_20200214_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiFacet',
            fields=[
                ('basefacet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ProductFilter.BaseFacet')),
            ],
            options={
                'abstract': False,
            },
            bases=('ProductFilter.basefacet',),
        ),
    ]
