# Generated by Django 2.2.1 on 2019-05-25 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0006_queryindex_dirty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfilter',
            name='sub_product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
