# Generated by Django 2.2.1 on 2019-06-28 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_product_installation_offered'),
        ('ProductFilter', '0007_auto_20190525_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryindex',
            name='dirty',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='FacetProductCollection',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('products', models.ManyToManyField(related_name='facet_collections', to='Products.Product')),
                ('query_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductFilter.QueryIndex')),
            ],
            options={
                'unique_together': {('query_index', 'name')},
            },
        ),
    ]
