# Generated by Django 2.2.1 on 2019-05-10 07:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0007_auto_20190510_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilter',
            name='color_field',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='productfilter',
            name='independent_range_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), blank=True, null=True, size=None),
        ),
    ]
