# Generated by Django 2.2.1 on 2019-06-28 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_product_installation_offered'),
        ('ProductFilter', '0008_auto_20190627_2113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacetProductCollection',
            new_name='FacetOthersCollection',
        ),
    ]
