# Generated by Django 2.2.1 on 2019-05-12 21:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0008_auto_20190510_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryindex',
            name='response',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
