# Generated by Django 2.2.1 on 2019-05-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0009_auto_20190512_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryindex',
            name='last_retrieved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='queryindex',
            name='times_accessed',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
