# Generated by Django 2.2.1 on 2019-06-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0009_auto_20190628_0226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facetotherscollection',
            old_name='name',
            new_name='facet_name',
        ),
        migrations.AlterUniqueTogether(
            name='facetotherscollection',
            unique_together={('query_index', 'facet_name')},
        ),
    ]
