# Generated by Django 2.2.1 on 2019-06-29 02:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ProductFilter', '0010_auto_20190628_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facetotherscollection',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
