# Generated by Django 2.0.6 on 2019-04-11 03:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profiles', '0001_initial'),
        ('Ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locationrating',
            unique_together={('user', 'location')},
        ),
    ]
