# Generated by Django 2.2.1 on 2019-07-06 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ratings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserProductCollections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationrating',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='UserProductCollections.RetailerLocation'),
        ),
        migrations.AddField(
            model_name='locationrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='productrating',
            unique_together={('user', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='locationrating',
            unique_together={('user', 'location')},
        ),
    ]
