# Generated by Django 3.0.3 on 2020-02-13 22:00

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.Product')),
                ('appliance_type', models.CharField(blank=True, max_length=100, null=True)),
                ('room_type', models.CharField(blank=True, max_length=100, null=True)),
                ('width', django.contrib.postgres.fields.ranges.DecimalRangeField(blank=True, null=True)),
                ('height', django.contrib.postgres.fields.ranges.DecimalRangeField(blank=True, null=True)),
                ('depth', django.contrib.postgres.fields.ranges.DecimalRangeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='Cabinets',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.Product')),
            ],
            options={
                'abstract': False,
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='FinishSurface',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.Product')),
                ('label_color', models.CharField(blank=True, max_length=50, null=True)),
                ('actual_color', models.CharField(blank=True, max_length=50, null=True)),
                ('finish', models.CharField(blank=True, max_length=200, null=True)),
                ('look', models.CharField(blank=True, max_length=200, null=True)),
                ('shade_variation', models.CharField(blank=True, max_length=200, null=True)),
                ('walls', models.BooleanField(default=False)),
                ('countertops', models.BooleanField(default=False)),
                ('floors', models.BooleanField(default=False)),
                ('cabinet_fronts', models.BooleanField(default=False)),
                ('shower_floors', models.BooleanField(default=False)),
                ('shower_walls', models.BooleanField(default=False)),
                ('exterior_walls', models.BooleanField(default=False)),
                ('exterior_floors', models.BooleanField(default=False)),
                ('covered_walls', models.BooleanField(default=False)),
                ('covered_floors', models.BooleanField(default=False)),
                ('pool_linings', models.BooleanField(default=False)),
                ('bullnose', models.BooleanField(default=False)),
                ('covebase', models.BooleanField(default=False)),
                ('corner_covebase', models.BooleanField(default=False)),
                ('thickness', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('width', django.contrib.postgres.fields.ranges.DecimalRangeField(blank=True, null=True)),
                ('length', django.contrib.postgres.fields.ranges.DecimalRangeField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=180, null=True)),
                ('actual_size', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('lrv', models.CharField(blank=True, max_length=60, null=True)),
                ('cof', models.CharField(max_length=60, null=True)),
                ('edge', models.CharField(blank=True, max_length=200, null=True)),
                ('end', models.CharField(blank=True, max_length=200, null=True)),
                ('install_type', models.CharField(max_length=100, null=True)),
                ('sqft_per_carton', models.CharField(max_length=70, null=True)),
                ('slip_resistant', models.BooleanField(default=False)),
                ('scale_width', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('scale_length', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('scale_thickness', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='CabinetLaminate',
            fields=[
                ('finishsurface_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SpecializedProducts.FinishSurface')),
            ],
            options={
                'abstract': False,
            },
            bases=('SpecializedProducts.finishsurface',),
        ),
        migrations.CreateModel(
            name='ColdStorage',
            fields=[
                ('appliance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SpecializedProducts.Appliance')),
            ],
            options={
                'abstract': False,
            },
            bases=('SpecializedProducts.appliance',),
        ),
        migrations.CreateModel(
            name='Hardwood',
            fields=[
                ('finishsurface_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SpecializedProducts.FinishSurface')),
                ('composition', models.CharField(blank=True, max_length=20, null=True)),
                ('species', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('SpecializedProducts.finishsurface',),
        ),
        migrations.CreateModel(
            name='LaminateFlooring',
            fields=[
                ('finishsurface_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SpecializedProducts.FinishSurface')),
                ('surface_coating', models.CharField(blank=True, max_length=80, null=True)),
                ('species', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('SpecializedProducts.finishsurface',),
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('appliance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SpecializedProducts.Appliance')),
            ],
            options={
                'abstract': False,
            },
            bases=('SpecializedProducts.appliance',),
        ),
        migrations.CreateModel(
            name='Resilient',
            fields=[
                ('finishsurface_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SpecializedProducts.FinishSurface')),
                ('surface_coating', models.CharField(blank=True, max_length=80, null=True)),
                ('shape', models.CharField(blank=True, max_length=20, null=True)),
                ('material_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('SpecializedProducts.finishsurface',),
        ),
        migrations.CreateModel(
            name='TileAndStone',
            fields=[
                ('finishsurface_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SpecializedProducts.FinishSurface')),
                ('shape', models.CharField(blank=True, max_length=40, null=True)),
                ('material_type', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('SpecializedProducts.finishsurface',),
        ),
    ]
