# Generated by Django 2.2.1 on 2019-10-14 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpecializedProducts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finishsurface',
            options={},
        ),
    ]
