# Generated by Django 2.2.1 on 2019-07-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpecializedProducts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finishsurface',
            options={'verbose_name': 'finish surfaces'},
        ),
    ]
