# Generated by Django 3.0.2 on 2020-01-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpecializedProducts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishsurface',
            name='scale_length',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='finishsurface',
            name='scale_thickness',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='finishsurface',
            name='scale_width',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
    ]
