# Generated by Django 2.2.1 on 2019-05-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinishSurfaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishsurface',
            name='actual_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finishsurface',
            name='label_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
