# Generated by Django 3.0.3 on 2020-02-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpecializedProducts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tileandstone',
            name='material_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tileandstone',
            name='shape',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
