# Generated by Django 3.0.3 on 2020-02-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpecializedProducts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabinets',
            options={'verbose_name': 'cabinets'},
        ),
    ]
