# Generated by Django 3.0.2 on 2020-01-22 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_auto_20200122_0146'),
        ('SpecializedProducts', '0002_auto_20200118_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.Product')),
                ('appliance_type', models.CharField(blank=True, max_length=100, null=True)),
                ('room_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='Cabinets',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.Product')),
            ],
            options={
                'abstract': False,
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.Product')),
            ],
            options={
                'abstract': False,
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='Lumber',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.Product')),
            ],
            options={
                'abstract': False,
            },
            bases=('Products.product',),
        ),
    ]
