# Generated by Django 3.0 on 2019-12-06 23:36

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpecializedProducts', '0002_auto_20191014_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishsurface',
            name='length',
            field=django.contrib.postgres.fields.ranges.DecimalRangeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finishsurface',
            name='width',
            field=django.contrib.postgres.fields.ranges.DecimalRangeField(blank=True, null=True),
        ),
    ]
