# Generated by Django 3.0.3 on 2020-02-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpecializedProducts', '0002_auto_20200217_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabinetlaminate',
            options={'verbose_name_plural': 'cabinet laminate'},
        ),
        migrations.AlterModelOptions(
            name='hardwood',
            options={'verbose_name_plural': 'hardwood'},
        ),
        migrations.AlterModelOptions(
            name='laminateflooring',
            options={'verbose_name_plural': 'laminate flooring'},
        ),
        migrations.AlterModelOptions(
            name='tileandstone',
            options={'verbose_name_plural': 'tile and stone'},
        ),
    ]
