# Generated by Django 3.0 on 2019-12-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpecializedProducts', '0003_auto_20191206_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishsurface',
            name='actual_size',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
