# Generated by Django 3.0.3 on 2020-02-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpecializedProducts', '0003_auto_20200217_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabinets',
            options={'verbose_name': 'cabinet', 'verbose_name_plural': 'cabinets'},
        ),
    ]
