# Generated by Django 3.0.2 on 2020-01-22 21:12

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpecializedProducts', '0003_appliance_cabinets_furniture_lumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='depth',
            field=django.contrib.postgres.fields.ranges.DecimalRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appliance',
            name='height',
            field=django.contrib.postgres.fields.ranges.DecimalRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appliance',
            name='width',
            field=django.contrib.postgres.fields.ranges.DecimalRangeField(blank=True, null=True),
        ),
    ]
