# Generated by Django 3.0 on 2019-12-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpecializedProducts', '0004_finishsurface_actual_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishsurface',
            name='size',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
