# Generated by Django 3.0.2 on 2020-02-04 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
        ('Suppliers', '0001_initial'),
        ('ProductFilter', '0002_auto_20200122_1918'),
        ('SpecializedProducts', '0004_auto_20200122_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lumber',
            name='product_ptr',
        ),
        migrations.DeleteModel(
            name='Furniture',
        ),
        migrations.DeleteModel(
            name='Lumber',
        ),
    ]
