# Generated by Django 3.0.3 on 2020-04-07 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Suppliers', '0004_supplierlocation_hash_value'),
        ('ProductFilter', '0007_filetypefacet'),
        ('Products', '0005_auto_20200227_0443'),
        ('Analytics', '0005_auto_20200323_1934'),
        ('Scraper', '0001_initial'),
        ('Profiles', '0004_auto_20200307_0243'),
        ('Search', '0006_auto_20200307_0243'),
        ('SpecializedProducts', '0004_auto_20200217_1736'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Range',
            new_name='Cooking',
        ),
        migrations.RenameModel(
            old_name='ColdStorage',
            new_name='Refrigeration',
        ),
    ]
