# Generated by Django 3.0.3 on 2020-04-07 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpecializedProducts', '0005_auto_20200407_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microwave',
            fields=[
                ('cooking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SpecializedProducts.Cooking')),
            ],
            options={
                'abstract': False,
            },
            bases=('SpecializedProducts.cooking',),
        ),
        migrations.CreateModel(
            name='Oven',
            fields=[
                ('cooking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SpecializedProducts.Cooking')),
            ],
            options={
                'abstract': False,
            },
            bases=('SpecializedProducts.cooking',),
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('cooking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SpecializedProducts.Cooking')),
            ],
            options={
                'abstract': False,
            },
            bases=('SpecializedProducts.cooking',),
        ),
    ]
