# Generated by Django 3.0.3 on 2020-04-09 23:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpecializedProducts', '0006_microwave_oven_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='appliance',
            name='colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='appliance',
            name='finishes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=70, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='cooking',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='burner_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
