# Generated by Django 3.0.3 on 2020-04-09 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpecializedProducts', '0007_auto_20200409_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliance',
            name='color',
        ),
    ]
