# Generated by Django 3.0.3 on 2020-04-10 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20200227_0443'),
        ('SpecializedProducts', '0008_remove_appliance_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliance',
            name='colors',
        ),
        migrations.CreateModel(
            name='ApplianceColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_value', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.Manufacturer')),
            ],
        ),
        migrations.AddField(
            model_name='appliance',
            name='colors',
            field=models.ManyToManyField(to='SpecializedProducts.ApplianceColor'),
        ),
    ]
