# Generated by Django 3.0.3 on 2020-04-27 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpecializedProducts', '0009_auto_20200410_0203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooking',
            options={'verbose_name_plural': 'cooking'},
        ),
        migrations.AlterModelOptions(
            name='refrigeration',
            options={'verbose_name_plural': 'refrigeration'},
        ),
    ]
