# Generated by Django 3.0.3 on 2020-05-17 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0006_auto_20200307_0243'),
        ('ProductFilter', '0007_filetypefacet'),
        ('Products', '0008_auto_20200429_2245'),
        ('Suppliers', '0004_supplierlocation_hash_value'),
        ('Analytics', '0005_auto_20200323_1934'),
        ('Profiles', '0004_auto_20200307_0243'),
        ('SpecializedProducts', '0010_auto_20200427_2351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cabinets',
        ),
    ]
