# Generated by Django 3.0.3 on 2020-05-17 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_auto_20200429_2245'),
        ('SpecializedProducts', '0011_delete_cabinets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lumber',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.Product')),
            ],
            options={
                'abstract': False,
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='Millwork',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.Product')),
            ],
            options={
                'verbose_name': 'millwork',
                'verbose_name_plural': 'millwork',
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('millwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SpecializedProducts.Millwork')),
            ],
            options={
                'verbose_name': 'cabinet',
                'verbose_name_plural': 'cabinets',
            },
            bases=('SpecializedProducts.millwork',),
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('millwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SpecializedProducts.Millwork')),
            ],
            options={
                'abstract': False,
            },
            bases=('SpecializedProducts.millwork',),
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('millwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SpecializedProducts.Millwork')),
            ],
            options={
                'abstract': False,
            },
            bases=('SpecializedProducts.millwork',),
        ),
        migrations.CreateModel(
            name='Framing',
            fields=[
                ('lumber_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SpecializedProducts.Lumber')),
            ],
            options={
                'abstract': False,
            },
            bases=('SpecializedProducts.lumber',),
        ),
        migrations.CreateModel(
            name='Plywood',
            fields=[
                ('lumber_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SpecializedProducts.Lumber')),
            ],
            options={
                'abstract': False,
            },
            bases=('SpecializedProducts.lumber',),
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('millwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SpecializedProducts.Millwork')),
            ],
            options={
                'abstract': False,
            },
            bases=('SpecializedProducts.millwork',),
        ),
    ]
