# Generated by Django 3.0.3 on 2020-05-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpecializedProducts', '0012_cabinet_column_door_framing_lumber_millwork_plywood_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='window',
            name='color',
            field=models.CharField(default='white', max_length=60),
        ),
        migrations.AddField(
            model_name='window',
            name='shape',
            field=models.CharField(default='retangular', max_length=60),
        ),
        migrations.AddField(
            model_name='window',
            name='structural_material',
            field=models.CharField(default='wood', max_length=60),
        ),
        migrations.AddField(
            model_name='window',
            name='style',
            field=models.CharField(default='casement', max_length=60),
        ),
        migrations.AddField(
            model_name='window',
            name='trim_material',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
