# Generated by Django 2.0.6 on 2018-06-22 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(help_text='Email', max_length=200)),
                ('first_name', models.CharField(help_text='First Name', max_length=50)),
                ('last_name', models.CharField(help_text='Last Name', max_length=50)),
                ('is_supplier', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Plans.Plan')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'is_supplier')},
        ),
    ]
