# Generated by Django 2.0.6 on 2018-06-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='user',
            name='date_confirmed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
