# Generated by Django 2.2.1 on 2019-08-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='demo',
            field=models.BooleanField(default=False),
        ),
    ]
