# Generated by Django 3.0.3 on 2020-03-07 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_user_current_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_zipcode',
        ),
    ]
