# Generated by Django 2.2.1 on 2019-10-03 00:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20191002_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 0, 28, 40, 675348, tzinfo=utc)),
        ),
    ]
