# Generated by Django 2.2.1 on 2019-10-03 22:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20191003_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 22, 47, 30, 665982, tzinfo=utc)),
        ),
    ]
