# Generated by Django 2.2.1 on 2019-10-04 03:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_auto_20191003_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 4, 3, 34, 20, 125955, tzinfo=utc)),
        ),
    ]
