# Generated by Django 2.2.1 on 2019-10-03 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profiles', '0003_auto_20191002_1834'),
        ('Groups', '0003_auto_20191002_2320'),
        ('Products', '0001_initial'),
        ('UserProductCollections', '0003_auto_20190920_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerCollaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=80, null=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='Profiles.ConsumerProfile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='UserProductCollections.BaseProject')),
            ],
        ),
        migrations.CreateModel(
            name='ProCollaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=80, null=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='Groups.ProCompany')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborations', to='Profiles.ProEmployeeProfile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_collaborators', to='UserProductCollections.BaseProject')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('quantity_needed', models.IntegerField()),
                ('procured', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='Products.Product')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_assignments', to='UserProductCollections.BaseProject')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='UserProductCollections.RetailerLocation')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('predecessor_type', models.CharField(choices=[('FTS', 'Finish to Start'), ('STS', 'Start to Start'), ('FTF', 'Finish to Finish')], default='FTS', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('progress', models.IntegerField(null=True)),
                ('level', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Schedule.ProjectTask')),
                ('predecessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependants', to='Schedule.ProjectTask')),
                ('pro_collaborator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Schedule.ProCollaborator')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='Schedule.ProductAssignment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='UserProductCollections.BaseProject')),
                ('user_collaborator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Schedule.ConsumerCollaborator')),
            ],
        ),
    ]
