# Generated by Django 2.2.1 on 2019-09-19 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        ('UserProductCollections', '0002_auto_20190914_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('quantity_needed', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='Products.Product')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_assignments', to='UserProductCollections.BaseProject')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='UserProductCollections.RetailerLocation')),
            ],
        ),
    ]
