# Generated by Django 2.2.1 on 2019-11-09 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProductCollections', '0003_auto_20190920_0628'),
        ('Groups', '0006_auto_20191014_2146'),
        ('Schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='procollaborator',
            unique_together={('project', 'collaborator')},
        ),
    ]
