# Generated by Django 2.2.1 on 2019-09-20 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_baseprofile_date_create'),
        ('UserProductCollections', '0003_auto_20190920_0628'),
        ('Groups', '0002_company_date_created'),
        ('Schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('predecessor_type', models.CharField(choices=[('FTS', 'Finish to Start'), ('STS', 'Start to Start'), ('FTF', 'Finish to Finish')], default='FTS', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Schedule.ProjectTask')),
                ('predecessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependants', to='Schedule.ProjectTask')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='Schedule.ProductAssignment')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='UserProductCollections.BaseProject')),
            ],
        ),
        migrations.CreateModel(
            name='ProCollaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=80, null=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='Groups.ProCompany')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborations', to='Profiles.ProEmployeeProfile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_collaborators', to='UserProductCollections.BaseProject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumerCollaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=80, null=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='Profiles.ConsumerProfile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='UserProductCollections.BaseProject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
