# Generated by Django 3.0 on 2019-12-29 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProducts', '0001_initial'),
        ('Schedule', '0002_auto_20191109_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='productassignment',
            name='supplier_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='UserProducts.RetailerProduct'),
        ),
    ]
