# Generated by Django 2.2.1 on 2019-09-21 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0002_consumercollaborator_procollaborator_projecttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='pro_collaborator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Schedule.ProCollaborator'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='user_collaborator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Schedule.ConsumerCollaborator'),
        ),
    ]
