# Generated by Django 3.0 on 2020-01-02 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0003_productassignment_supplier_product'),
    ]

    database_operations = [
        migrations.AlterModelTable('ProductAssignment', 'projects__baseproject'),
        migrations.AlterModelTable('ProjectTask', 'projects__proproject'),
        migrations.AlterModelTable('ProCollaborator', 'projects__consumerproject'),
        migrations.AlterModelTable('ConsumerCollaborator', 'retailers__retailerLocation')
        ]

    state_operations = [
        migrations.DeleteModel('BaseProject'),
        migrations.DeleteModel('ProProject'),
        migrations.DeleteModel('ConsumerProject'),
        migrations.DeleteModel('RetailerLocation')
        ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        )
        ]
