# Generated by Django 2.2.1 on 2019-09-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0004_auto_20190921_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productassignment',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
