# Generated by Django 2.2.1 on 2019-09-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProductCollections', '0003_auto_20190920_0628'),
        ('Schedule', '0005_auto_20190921_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productassignment',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterUniqueTogether(
            name='productassignment',
            unique_together={('project', 'name')},
        ),
    ]
