# Generated by Django 2.2.1 on 2019-09-21 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0006_auto_20190921_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productassignment',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='UserProductCollections.RetailerLocation'),
        ),
    ]
