# Generated by Django 2.2.1 on 2019-09-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0007_auto_20190921_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='progress',
            field=models.IntegerField(null=True),
        ),
    ]
