# Generated by Django 2.2.1 on 2019-09-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0008_projecttask_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
