# Generated by Django 2.2.1 on 2019-09-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0009_projecttask_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='productassignment',
            name='procured',
            field=models.BooleanField(default=False),
        ),
    ]
