# Generated by Django 2.0.6 on 2019-05-08 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerProfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_products', to='Products.Product'),
        ),
    ]
