# Generated by Django 2.0.6 on 2019-03-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerProfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproject',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerproject',
            name='template',
            field=models.BooleanField(default=False),
        ),
    ]
