# Generated by Django 2.0.6 on 2019-02-14 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
        ('CustomerProfiles', '0002_auto_20190120_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProjectApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customerproject',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='Addresses.Address'),
        ),
        migrations.AlterField(
            model_name='customerproject',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='customerproduct',
            name='use',
        ),
        migrations.AlterUniqueTogether(
            name='customerproduct',
            unique_together={('product', 'project')},
        ),
        migrations.AddField(
            model_name='customerprojectapplication',
            name='products',
            field=models.ManyToManyField(to='CustomerProfiles.CustomerProduct'),
        ),
        migrations.AddField(
            model_name='customerprojectapplication',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='CustomerProfiles.CustomerProject'),
        ),
        migrations.AlterUniqueTogether(
            name='customerprojectapplication',
            unique_together={('label', 'project')},
        ),
    ]
