# Generated by Django 2.0.6 on 2019-03-14 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerProfiles', '0003_auto_20190214_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprojectapplication',
            name='products',
            field=models.ManyToManyField(blank=True, to='CustomerProfiles.CustomerProduct'),
        ),
        migrations.AlterField(
            model_name='customerprojectapplication',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='CustomerProfiles.CustomerProject'),
        ),
    ]
