# Generated by Django 2.2.1 on 2019-12-01 23:50
# edited manually to move linrarylink table instead of newly create

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BBadmin', '0010_auto_20191201_2344')
    ]

    state_operations = [
        migrations.CreateModel(
            name='LibraryLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('Analytics', 'Analytics'), ('Projects', 'Projects'), ('Locations', 'Locations'), ('Profile', 'Profile'), ('Company_Info', 'Company_Info'), ('Admin', 'Admin')], max_length=18, unique=True)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('draw_path', models.TextField(blank=True, null=True)),
                ('display', models.FileField(blank=True, null=True, upload_to='misc/')),
                ('for_user', models.BooleanField(default=False)),
                ('for_pro', models.BooleanField(default=False)),
                ('for_supplier', models.BooleanField(default=False)),
                ('for_admin', models.BooleanField(default=False)),
                ],
            ),
        ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
        ]
