# Generated by Django 3.0.3 on 2020-02-12 05:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=18, unique=True)),
                ('link', models.CharField(default='', max_length=18)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('draw_path', models.TextField(blank=True, null=True)),
                ('display', models.FileField(blank=True, null=True, upload_to='misc/')),
                ('include_collections', models.BooleanField(default=False)),
                ('for_user', models.BooleanField(default=False)),
                ('for_supplier', models.BooleanField(default=False)),
                ('for_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('draw_path', models.TextField(blank=True, null=True)),
                ('display', models.FileField(blank=True, null=True, upload_to='misc/')),
            ],
        ),
        migrations.CreateModel(
            name='UserTypeStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=150, null=True)),
                ('display_image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='misc/')),
                ('tagline', models.CharField(blank=True, max_length=300, null=True)),
                ('full_text', models.TextField(blank=True, null=True)),
                ('include_options', models.BooleanField(default=False)),
                ('feature', models.ManyToManyField(blank=True, related_name='ut_static', to='config.UserFeature')),
            ],
        ),
        migrations.CreateModel(
            name='SubclassTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('content_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
