# Generated by Django 2.2.1 on 2019-12-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTypeStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=150, null=True)),
                ('display_image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='misc/')),
                ('tagline', models.CharField(blank=True, max_length=300, null=True)),
                ('full_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
