# Generated by Django 3.0 on 2020-01-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarylink',
            name='label',
            field=models.CharField(choices=[('admin', 'admin'), ('company_info', 'company_info'), ('all_collaborators', 'all_collaborators'), ('all_materials', 'all_materials'), ('projects', 'projects'), ('locations', 'locations'), ('profile', 'profile')], max_length=18, unique=True),
        ),
    ]
