# Generated by Django 3.0.3 on 2020-02-17 16:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_tree', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('supplier_tree', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SubclassTree',
        ),
    ]
