# Generated by Django 2.2.1 on 2019-12-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_usertypestatic'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('draw_path', models.TextField(blank=True, null=True)),
                ('display', models.FileField(blank=True, null=True, upload_to='misc/')),
                ('for_user', models.BooleanField(default=False)),
                ('for_pro', models.BooleanField(default=False)),
                ('for_supplier', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='usertypestatic',
            name='feature',
            field=models.ManyToManyField(related_name='ut_static', to='config.UserFeature'),
        ),
    ]
