# Generated by Django 3.0.3 on 2020-02-11 22:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_subclasstree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subclasstree',
            name='tree',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
