# Generated by Django 3.0.3 on 2020-04-07 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20200217_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='configtree',
            name='late_refreshed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
