# Generated by Django 2.2.1 on 2019-12-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20191202_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeature',
            name='for_pro',
        ),
        migrations.RemoveField(
            model_name='userfeature',
            name='for_supplier',
        ),
        migrations.RemoveField(
            model_name='userfeature',
            name='for_user',
        ),
        migrations.AlterField(
            model_name='usertypestatic',
            name='feature',
            field=models.ManyToManyField(blank=True, null=True, related_name='ut_static', to='config.UserFeature'),
        ),
    ]
