# Generated by Django 3.0.3 on 2020-04-07 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_configtree_late_refreshed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configtree',
            old_name='late_refreshed',
            new_name='last_refreshed',
        ),
    ]
