# Generated by Django 2.2.1 on 2019-12-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20191202_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertypestatic',
            name='include_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usertypestatic',
            name='feature',
            field=models.ManyToManyField(blank=True, related_name='ut_static', to='config.UserFeature'),
        ),
    ]
