# Generated by Django 3.0 on 2019-12-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_auto_20191202_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarylink',
            name='label',
            field=models.CharField(choices=[('Analytics', 'Analytics'), ('Projects', 'Projects'), ('Locations', 'Locations'), ('Profile', 'Profile'), ('Company_Info', 'Company_Info'), ('Admin', 'Admin'), ('Dashboard', 'Dashboard')], max_length=18, unique=True),
        ),
    ]
