# Generated by Django 3.0.3 on 2020-04-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_auto_20200407_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertypestatic',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='misc/'),
        ),
    ]
