# Generated by Django 3.0.3 on 2020-05-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_usertypestatic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeature',
            name='supplier',
            field=models.BooleanField(default=False),
        ),
    ]
