# Generated by Django 3.0 on 2020-01-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_auto_20191229_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarylink',
            name='include_collections',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='librarylink',
            name='link',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='librarylink',
            name='label',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Company_Info', 'Company_Info'), ('Collaborators', 'Collaborators'), ('Materials', 'Materials'), ('Projects', 'Projects'), ('Profile', 'Profile'), ('Dashboard', 'Dashboard')], max_length=18, unique=True),
        ),
    ]
