# Generated by Django 3.0.3 on 2020-05-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_userfeature_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='misc/'),
        ),
    ]
