# Generated by Django 3.0.3 on 2020-05-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_userfeature_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeature',
            name='display',
        ),
        migrations.RemoveField(
            model_name='userfeature',
            name='draw_path',
        ),
        migrations.AlterField(
            model_name='userfeature',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userfeature',
            name='label',
            field=models.CharField(max_length=140, unique=True),
        ),
    ]
