# Generated by Django 2.2.1 on 2019-08-25 23:29

import config.settings.local_storage
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperAggregateProductRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.IntegerField()),
                ('rating_max', models.IntegerField(default=5)),
                ('rating_count', models.IntegerField()),
                ('product_bbsku', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScraperCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('unit', models.CharField(choices=[('SF', 'SF'), ('Each', 'Each')], default='SF', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ScraperDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='ScraperManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ScraperSubgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_scraping_url', models.URLField(blank=True, max_length=2000)),
                ('scraped', models.BooleanField(default=False)),
                ('cleaned', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroup', to='Scraper.ScraperCategory')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroup', to='Scraper.ScraperManufacturer')),
            ],
            options={
                'unique_together': {('manufacturer', 'category')},
            },
        ),
        migrations.AddField(
            model_name='scrapercategory',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='Scraper.ScraperDepartment'),
        ),
        migrations.CreateModel(
            name='ScraperBaseProduct',
            fields=[
                ('name', models.CharField(max_length=1000)),
                ('manufacturer_sku', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('manufacturer_collection', models.CharField(blank=True, max_length=200)),
                ('manufacturer_style', models.CharField(blank=True, max_length=200)),
                ('product_url', models.URLField(default='', max_length=500)),
                ('swatch_image_original', models.URLField(blank=True, max_length=500)),
                ('room_scene_original', models.URLField(blank=True, max_length=500, null=True)),
                ('tiling_scene_original', models.URLField(blank=True, max_length=500, null=True)),
                ('swatch_image_local', models.ImageField(null=True, storage=config.settings.local_storage.LocalStorage(location='D:\\BSData\\product_images'), upload_to='swatches/')),
                ('room_scene_local', models.ImageField(null=True, storage=config.settings.local_storage.LocalStorage(location='D:\\BSData\\product_images'), upload_to='rooms/')),
                ('tiling_scene_local', models.ImageField(null=True, storage=config.settings.local_storage.LocalStorage(location='D:\\BSData\\product_images'), upload_to='tiles/')),
                ('swatch_image_final', models.ImageField(null=True, upload_to='swatches/')),
                ('room_scene_final', models.ImageField(null=True, upload_to='rooms/')),
                ('tiling_scene_final', models.ImageField(null=True, upload_to='tiles/')),
                ('residential_warranty', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('commercial_warranty', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('light_commericial_warranty', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modiefied', models.DateTimeField(auto_now=True)),
                ('commercial', models.BooleanField(default=False)),
                ('bb_sku', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Scraper.ScraperSubgroup')),
            ],
        ),
    ]
