# Generated by Django 3.0.3 on 2020-02-13 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=70)),
                ('scraped', models.BooleanField(default=False)),
                ('base_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('category', models.ForeignKey(limit_choices_to={'app_label': 'SpecializedProducts'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Manufacturer')),
            ],
        ),
    ]
