# Generated by Django 2.2.1 on 2019-05-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapersubgroup',
            name='cleaned',
            field=models.BooleanField(default=False),
        ),
    ]
