# Generated by Django 2.2.1 on 2019-06-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scraper', '0002_scrapersubgroup_cleaned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperbaseproduct',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
