# Generated by Django 3.0.3 on 2020-04-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scraper', '0002_scrapergroup_images_obtained'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapergroup',
            name='geometry_obtained',
            field=models.BooleanField(default=False),
        ),
    ]
