# Generated by Django 3.0.3 on 2020-02-11 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Plans', '0001_initial'),
        ('Addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('info', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='storefronts/')),
                ('business_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Addresses.Address')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='Plans.SupplierPlan')),
            ],
        ),
    ]
