# Generated by Django 3.0 on 2020-01-02 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Plans', '0001_initial'),
        ('Addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='misc/')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('info', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='storefronts/')),
                ('business_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Addresses.Address')),
            ],
        ),
        migrations.CreateModel(
            name='RetailerCompany',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Groups.Company')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='Plans.RetailerPlan')),
            ],
            bases=('Groups.company',),
        ),
        migrations.CreateModel(
            name='ProCompany',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Groups.Company')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='Plans.ProPlan')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Groups.ServiceType')),
            ],
            bases=('Groups.company',),
        ),
    ]
