# Generated by Django 3.0.3 on 2020-03-03 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Addresses', '0002_address_demo'),
        ('Groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliercompany',
            name='business_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Addresses.Address'),
        ),
    ]
