# Generated by Django 3.0.3 on 2020-07-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0002_auto_20200303_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercompany',
            name='background_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
