# Generated by Django 2.2.1 on 2019-10-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0003_auto_20191002_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='storefronts/'),
        ),
    ]
