# Generated by Django 2.2.1 on 2019-10-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0004_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='misc/'),
        ),
    ]
