# Generated by Django 2.2.1 on 2019-10-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0005_auto_20191014_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
