# Generated by Django 3.0.3 on 2020-02-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('return_url', models.CharField(max_length=200)),
                ('hash_value', models.CharField(max_length=2000)),
            ],
        ),
    ]
