# Generated by Django 3.0.3 on 2020-02-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchindex',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
