# Generated by Django 3.0.3 on 2020-02-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0002_auto_20200225_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchindex',
            name='hash_value',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
