# Generated by Django 3.0.3 on 2020-02-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0003_auto_20200226_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchindex',
            name='in_department',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
