# Generated by Django 3.0.3 on 2020-03-06 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Suppliers', '0004_supplierlocation_hash_value'),
        ('Products', '0005_auto_20200227_0443'),
        ('Search', '0004_searchindex_in_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchindex',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.Product'),
        ),
        migrations.AddField(
            model_name='searchindex',
            name='supplier_location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Suppliers.SupplierLocation'),
        ),
    ]
