# Generated by Django 3.0.3 on 2020-03-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0005_auto_20200306_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchindex',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='searchindex',
            unique_together={('name', 'in_department')},
        ),
    ]
