# Generated by Django 2.2.1 on 2019-08-30 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Addresses', '0001_initial'),
        ('Profiles', '0001_initial'),
        ('Groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=60)),
                ('approved_in_store_seller', models.BooleanField(default=False)),
                ('approved_online_seller', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='storefronts/')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retailer_locations', to='Addresses.Address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_locations', to='Groups.RetailerCompany')),
                ('local_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_locations', to='Profiles.RetailerEmployeeProfile')),
            ],
        ),
        migrations.CreateModel(
            name='BaseProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('template', models.BooleanField(default=False)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='Addresses.Address')),
                ('collaborators', models.ManyToManyField(to='Profiles.ConsumerProfile')),
                ('pro_collaborator', models.ManyToManyField(to='Profiles.ProEmployeeProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ProProject',
            fields=[
                ('baseproject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserProductCollections.BaseProject')),
                ('nickname', models.CharField(max_length=60)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Groups.ProCompany')),
            ],
            options={
                'unique_together': {('nickname', 'owner')},
            },
            bases=('UserProductCollections.baseproject',),
        ),
        migrations.CreateModel(
            name='ConsumerProject',
            fields=[
                ('baseproject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='UserProductCollections.BaseProject')),
                ('nickname', models.CharField(max_length=60)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Profiles.ConsumerProfile')),
            ],
            options={
                'unique_together': {('nickname', 'owner')},
            },
            bases=('UserProductCollections.baseproject',),
        ),
    ]
