# Generated by Django 2.2.1 on 2019-09-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0002_company_date_created'),
        ('UserProductCollections', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='retailerlocation',
            unique_together={('nickname', 'company')},
        ),
    ]
