# Generated by Django 2.2.1 on 2019-07-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProductCollections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailerlocation',
            name='info',
        ),
    ]
