# Generated by Django 2.2.1 on 2019-09-20 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProductCollections', '0002_auto_20190914_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseproject',
            name='collaborators',
        ),
        migrations.RemoveField(
            model_name='baseproject',
            name='pro_collaborator',
        ),
    ]
