# Generated by Django 2.2.1 on 2019-08-04 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProductCollections', '0002_remove_retailerlocation_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailerlocation',
            name='local_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_locations', to='Profiles.RetailerEmployeeProfile'),
        ),
    ]
