# Generated by Django 3.0 on 2019-12-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProductCollections', '0003_auto_20190920_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project-images/'),
        ),
    ]
