# Generated by Django 2.2.1 on 2019-08-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProductCollections', '0003_auto_20190804_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailerlocation',
            name='phone_number',
            field=models.CharField(max_length=16),
        ),
    ]
