# Generated by Django 3.0 on 2020-01-02 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProductCollections', '0004_baseproject_image'),
    ]

    database_operations = [
        migrations.AlterModelTable('BaseProject', 'projects__baseproject'),
        migrations.AlterModelTable('ProProject', 'projects__proproject'),
        migrations.AlterModelTable('ConsumerProject', 'projects__consumerproject'),
        migrations.AlterModelTable('RetailerLocation', 'retailers__retailerLocation')
        ]

    state_operations = [
        migrations.DeleteModel('BaseProject'),
        migrations.DeleteModel('ProProject'),
        migrations.DeleteModel('ConsumerProject'),
        migrations.DeleteModel('RetailerLocation')
        ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        )
    ]
