# Generated by Django 2.0.6 on 2019-03-24 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('productsubclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.ProductSubClass')),
                ('name', models.CharField(max_length=10)),
            ],
            bases=('Products.productsubclass',),
        ),
    ]
