# Generated by Django 2.2.1 on 2019-10-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('Analytics', 'Analytics'), ('Projects', 'Projects'), ('Locations', 'Locations'), ('Profile', 'Profile'), ('Company Info', 'Company Info')], max_length=18, unique=True)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('display', models.FileField(upload_to='misc/')),
                ('for_user', models.BooleanField(default=False)),
                ('for_pro', models.BooleanField(default=False)),
                ('for_supplier', models.BooleanField(default=False)),
            ],
        ),
    ]
