# Generated by Django 2.2.1 on 2019-10-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarylink',
            name='draw_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
