# Generated by Django 2.2.1 on 2019-10-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBadmin', '0002_librarylink_draw_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarylink',
            name='draw_path',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
