# Generated by Django 2.2.1 on 2019-10-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBadmin', '0003_auto_20191031_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarylink',
            name='draw_path',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
