# Generated by Django 2.2.1 on 2019-10-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBadmin', '0005_auto_20191031_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarylink',
            name='draw_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
