# Generated by Django 2.2.1 on 2019-11-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBadmin', '0006_auto_20191031_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarylink',
            name='label',
            field=models.CharField(choices=[('Analytics', 'Analytics'), ('Projects', 'Projects'), ('Locations', 'Locations'), ('Profile', 'Profile'), ('Company_Info', 'Company_Info')], max_length=18, unique=True),
        ),
    ]
