# Generated by Django 2.2.1 on 2019-11-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBadmin', '0007_auto_20191109_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarylink',
            name='for_admin',
            field=models.BooleanField(default=False),
        ),
    ]
