# Generated by Django 2.2.1 on 2019-11-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBadmin', '0008_librarylink_for_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarylink',
            name='display',
            field=models.FileField(blank=True, null=True, upload_to='misc/'),
        ),
        migrations.AlterField(
            model_name='librarylink',
            name='label',
            field=models.CharField(choices=[('Analytics', 'Analytics'), ('Projects', 'Projects'), ('Locations', 'Locations'), ('Profile', 'Profile'), ('Company_Info', 'Company_Info'), ('Admin', 'Admin')], max_length=18, unique=True),
        ),
    ]
