# Generated by Django 2.2.1 on 2019-12-01 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BBadmin', '0009_auto_20191129_1549'),
    ]

    database_operations = [migrations.AlterModelTable('LibraryLink', 'config_librarylink')]

    state_operations = [migrations.DeleteModel('LibraryLink')]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        )
    ]
