# Generated by Django 2.0.6 on 2018-08-20 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('unit', models.CharField(choices=[('Square Foot', 'Square Foot'), ('Linear Foot', 'Linear Foot'), ('Cubic Foot', 'Cubic Foot'), ('Each', 'Each')], default='not assigned', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Look',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='Products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manufacturer_url', models.URLField(blank=True, null=True)),
                ('lowest_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_priced', models.BooleanField(default=False)),
                ('for_sale', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='')),
                ('walls', models.BooleanField(default=False)),
                ('countertops', models.BooleanField(default=False)),
                ('floors', models.BooleanField(default=False)),
                ('shower', models.BooleanField(default=False)),
                ('exterior', models.BooleanField(default=False)),
                ('covered', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('thickness', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('manufacturer_sku', models.CharField(blank=True, max_length=50, null=True)),
                ('manu_collection', models.CharField(blank=True, max_length=50, null=True)),
                ('image_2', models.ImageField(null=True, upload_to='')),
                ('lrv', models.IntegerField(null=True)),
                ('cof', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('width', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('length', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Build')),
                ('look', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.Look')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Products.Manufacturer')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.Material')),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='build_types', to='Products.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('category', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='build',
            unique_together={('category', 'label')},
        ),
    ]
