# Generated by Django 3.0.3 on 2020-02-11 08:06

import Products.models
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(blank=True, max_length=1200)),
                ('bb_sku', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('hash_value', models.CharField(blank=True, max_length=1200, null=True, unique=True)),
                ('unit', models.CharField(blank=True, choices=[('SF', 'SF'), ('EACH', 'Each')], default='SF', max_length=10)),
                ('category', models.CharField(editable=False, max_length=60, null=True)),
                ('manufacturer_url', models.URLField(blank=True, max_length=300, null=True)),
                ('manufacturer_sku', models.CharField(blank=True, max_length=200, null=True)),
                ('manufacturer_collection', models.CharField(blank=True, max_length=200, null=True)),
                ('manufacturer_style', models.CharField(blank=True, max_length=200, null=True)),
                ('swatch_image', models.ImageField(upload_to='swatches/')),
                ('room_scene', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('tiling_image', models.ImageField(blank=True, null=True, upload_to='tiles/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('in_store', models.BooleanField(default=False)),
                ('online_and_priced', models.BooleanField(default=False)),
                ('in_store_and_priced', models.BooleanField(default=False)),
                ('installation_offered', models.BooleanField(default=False)),
                ('locations', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
                ('residential_warranty', models.CharField(blank=True, max_length=100, null=True)),
                ('commercial_warranty', models.CharField(blank=True, max_length=100, null=True)),
                ('light_commercial_warranty', models.CharField(blank=True, max_length=100, null=True)),
                ('commercial', models.BooleanField(default=False)),
                ('_dxf_file', models.FileField(blank=True, null=True, upload_to=Products.models.get_3d_return_path)),
                ('_rfa_file', models.FileField(blank=True, null=True, upload_to=Products.models.get_3d_return_path)),
                ('_ipt_file', models.FileField(blank=True, null=True, upload_to=Products.models.get_3d_return_path)),
                ('_dwg_3d_file', models.FileField(blank=True, null=True, upload_to=Products.models.get_3d_return_path)),
                ('_dwg_2d_file', models.FileField(blank=True, null=True, upload_to=Products.models.get_3d_return_path)),
                ('_obj_file', models.FileField(blank=True, null=True, upload_to=Products.models.get_3d_return_path)),
                ('_mtl_file', models.FileField(blank=True, null=True, upload_to=Products.models.get_3d_return_path)),
                ('dxf_file', models.URLField(blank=True, max_length=1000, null=True)),
                ('rfa_file', models.URLField(blank=True, max_length=1000, null=True)),
                ('ipt_file', models.URLField(blank=True, max_length=1000, null=True)),
                ('dwg_3d_file', models.URLField(blank=True, max_length=1000, null=True)),
                ('dwg_2d_file', models.URLField(blank=True, max_length=1000, null=True)),
                ('obj_file', models.URLField(blank=True, max_length=1000, null=True)),
                ('mtl_file', models.URLField(blank=True, max_length=1000, null=True)),
                ('derived_gbl', models.FileField(blank=True, null=True, upload_to=Products.models.get_3d_return_path)),
                ('derived_width', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('derived_height', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('derived_depth', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('derived_center', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=3)),
                ('geometry_clean', models.BooleanField(default=False)),
                ('detail_response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Products.Manufacturer')),
            ],
            options={
                'unique_together': {('manufacturer', 'manufacturer_sku')},
            },
        ),
    ]
