# Generated by Django 2.0.6 on 2018-07-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_priced',
            field=models.BooleanField(default=False),
        ),
    ]
