# Generated by Django 2.0.6 on 2018-12-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='covered',
            new_name='covered_floors',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='exterior',
            new_name='exterior_floors',
        ),
        migrations.AddField(
            model_name='product',
            name='covered_walls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='exterior_walls',
            field=models.BooleanField(default=False),
        ),
    ]
