# Generated by Django 2.0.6 on 2018-07-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='unit',
            field=models.CharField(choices=[('Square Foot', 'Square Foot'), ('Linear Foot', 'Linear Foot'), ('Cubic Foot', 'Cubic Foot'), ('Each', 'Each')], default='not assigned', max_length=50),
        ),
    ]
