# Generated by Django 2.0.6 on 2018-09-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=300, null=True, upload_to=''),
        ),
    ]
