# Generated by Django 2.2.1 on 2019-05-17 02:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='notes',
        ),
        migrations.AddField(
            model_name='product',
            name='detail_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
