# Generated by Django 2.0.6 on 2018-11-22 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='name',
            new_name='label',
        ),
    ]
