# Generated by Django 2.0.6 on 2019-05-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinishSurfaces', '0002_auto_20190504_1546'),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
        migrations.DeleteModel(
            name='ProductSubClass',
        ),
    ]
