# Generated by Django 2.0.6 on 2019-05-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='bb_sku',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
