# Generated by Django 3.0.3 on 2020-02-13 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Scraper', '0001_initial'),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='scraper_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Scraper.ScraperGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('manufacturer', 'manufacturer_sku')},
        ),
    ]
