# Generated by Django 3.0 on 2020-01-08 20:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='locations',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='product',
            name='room_scene',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='tiling_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
