# Generated by Django 2.0.6 on 2018-08-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commercial_warranty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='residential_warranty',
            field=models.IntegerField(null=True),
        ),
    ]
