# Generated by Django 3.0.2 on 2020-01-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gltf_file',
            field=models.FileField(blank=True, null=True, upload_to='gtlf/'),
        ),
        migrations.AddField(
            model_name='product',
            name='obj_file',
            field=models.FileField(blank=True, null=True, upload_to='objs/'),
        ),
    ]
