# Generated by Django 2.0.6 on 2019-04-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
