# Generated by Django 2.0.6 on 2019-01-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='resized',
            field=models.BooleanField(default=False),
        ),
    ]
