# Generated by Django 2.0.6 on 2018-12-28 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='actual_color',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='commercial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='install_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='light_commercial_warranty',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shade',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slip_resistant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sqft_per_carton',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='commercial_warranty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='residential_warranty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='edge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.Edge'),
        ),
    ]
