# Generated by Django 2.0.6 on 2019-03-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20190314_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('SF', 'SF'), ('EACH', 'Each')], default='SF', max_length=10),
        ),
    ]
