# Generated by Django 2.2.1 on 2019-06-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20190516_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='installation_offered',
            field=models.BooleanField(default=False),
        ),
    ]
