# Generated by Django 2.0.6 on 2018-12-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20181227_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sqft_per_carton',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
