# Generated by Django 2.0.6 on 2018-08-20 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20180820_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pool',
            new_name='pool_linings',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='shower',
            new_name='shower_floors',
        ),
        migrations.AddField(
            model_name='product',
            name='shower_walls',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='cof',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='commercial_warranty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='look',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.Look'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lrv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='residential_warranty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
