# Generated by Django 2.0.6 on 2018-12-22 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20181211_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SurfaceCoating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SurfaceTexture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='build',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='build',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='build',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_2',
        ),
        migrations.AddField(
            model_name='finish',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finishes', to='Products.Material'),
        ),
        migrations.AddField(
            model_name='product',
            name='room_scene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reoom_scenes', to='Products.Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='swatch_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swatches', to='Products.Image'),
        ),
        migrations.AlterField(
            model_name='finish',
            name='label',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='material',
            name='label',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='bb_sku',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cof',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='finish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.Finish'),
        ),
        migrations.AlterField(
            model_name='product',
            name='look',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.Look'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lowest_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer_color',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='finish',
            unique_together={('material', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='Build',
        ),
        migrations.AddField(
            model_name='surfacetexture',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='textures', to='Products.Material'),
        ),
        migrations.AddField(
            model_name='surfacecoating',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coatings', to='Products.Material'),
        ),
        migrations.AddField(
            model_name='submaterial',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='Products.Material'),
        ),
        migrations.RemoveField(
            model_name='material',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='sub_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.SubMaterial'),
        ),
        migrations.AddField(
            model_name='product',
            name='surface_coating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.SurfaceCoating'),
        ),
        migrations.AddField(
            model_name='product',
            name='surface_texture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.SurfaceTexture'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterUniqueTogether(
            name='surfacetexture',
            unique_together={('material', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='surfacecoating',
            unique_together={('material', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='submaterial',
            unique_together={('material', 'label')},
        ),
    ]
