# Generated by Django 2.0.6 on 2018-10-21 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20180924_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='for_sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_priced',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lowest_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='shade_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.ShadeVariation'),
        ),
    ]
