# Generated by Django 2.0.6 on 2018-08-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_product_manufacturer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
