# Generated by Django 2.0.6 on 2018-11-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addresses', '0002_auto_20181126_2204'),
        ('Products', '0002_auto_20181122_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='locations',
            field=models.ManyToManyField(to='Addresses.Coordinate'),
        ),
    ]
