# Generated by Django 3.0.2 on 2020-01-17 20:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20200117_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dae_file',
            field=models.FileField(blank=True, null=True, upload_to='dae/'),
        ),
        migrations.AddField(
            model_name='product',
            name='geometry_clean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='ipt_file',
            field=models.FileField(blank=True, null=True, upload_to='ipt/'),
        ),
        migrations.AddField(
            model_name='product',
            name='rvt_file',
            field=models.FileField(blank=True, null=True, upload_to='rvt/'),
        ),
        migrations.AddField(
            model_name='product',
            name='stl_file',
            field=models.FileField(blank=True, null=True, upload_to='stl/'),
        ),
        migrations.AddField(
            model_name='product',
            name='three_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
