# Generated by Django 2.0.6 on 2019-01-07 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_product_resized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='resized',
        ),
    ]
