# Generated by Django 2.0.6 on 2018-07-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_product_is_priced'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lowest_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
