# Generated by Django 2.0.6 on 2018-12-29 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20181228_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tiling_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiling_images', to='Products.Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='room_scene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_scenes', to='Products.Image'),
        ),
    ]
