# Generated by Django 2.0.6 on 2018-07-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_product_lowest_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lowest_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
