# Generated by Django 2.0.6 on 2018-10-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20181021_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='for_sale_in_store',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='for_sale_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='lowest_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
