# Generated by Django 3.0.3 on 2020-02-25 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_initialproductvalues_valuecleaner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
