# Generated by Django 2.0.6 on 2018-11-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_product_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='unit',
        ),
    ]
