# Generated by Django 3.0.2 on 2020-01-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20200117_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_dae_file',
            field=models.FileField(blank=True, null=True, upload_to='dae/'),
        ),
        migrations.AddField(
            model_name='product',
            name='initial_gltf_file',
            field=models.FileField(blank=True, null=True, upload_to='gtlf/'),
        ),
        migrations.AddField(
            model_name='product',
            name='initial_ipt_file',
            field=models.FileField(blank=True, null=True, upload_to='ipt/'),
        ),
        migrations.AddField(
            model_name='product',
            name='initial_mtl_file',
            field=models.FileField(blank=True, null=True, upload_to='objs/'),
        ),
        migrations.AddField(
            model_name='product',
            name='initial_obj_file',
            field=models.FileField(blank=True, null=True, upload_to='objs/'),
        ),
        migrations.AddField(
            model_name='product',
            name='initial_rvt_file',
            field=models.FileField(blank=True, null=True, upload_to='rvt/'),
        ),
        migrations.AddField(
            model_name='product',
            name='initial_stl_file',
            field=models.FileField(blank=True, null=True, upload_to='stl/'),
        ),
        migrations.AddField(
            model_name='product',
            name='mtl_file',
            field=models.FileField(blank=True, null=True, upload_to='objs/'),
        ),
    ]
