# Generated by Django 2.2.1 on 2019-06-29 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_product_installation_offered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='for_sale_in_store',
            new_name='in_store_and_priced',
        ),
    ]
