# Generated by Django 2.0.6 on 2018-12-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20181228_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lrv',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
