# Generated by Django 2.0.6 on 2018-12-03 23:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_remove_build_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='locations',
        ),
        migrations.AddField(
            model_name='product',
            name='locations',
            field=django.contrib.gis.db.models.fields.MultiPointField(null=True, srid=4326),
        ),
    ]
