# Generated by Django 2.2.1 on 2019-06-29 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20190628_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='for_sale_online',
            new_name='online_and_priced',
        ),
    ]
