# Generated by Django 3.0.3 on 2020-02-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuecleaner',
            name='initial_value',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='valuecleaner',
            unique_together={('product', 'field')},
        ),
    ]
