# Generated by Django 2.0.6 on 2018-11-05 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20181021_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bb_sku',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='finish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.Finish'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
