# Generated by Django 2.0.6 on 2018-07-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20180719_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
