# Generated by Django 3.0.2 on 2020-01-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20200120_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='initial_dae_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='initial_gltf_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='initial_ipt_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='initial_mtl_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='initial_obj_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='initial_rvt_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='initial_stl_file',
        ),
        migrations.AddField(
            model_name='product',
            name='dae_file_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gltf_file_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mtl_file_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='obj_file_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stl_file_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
