# Generated by Django 2.0.6 on 2018-08-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20180815_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manu_collection',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
