# Generated by Django 3.0.3 on 2020-04-10 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20200227_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='scraper_group',
        ),
    ]
