# Generated by Django 3.0.2 on 2020-01-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20200121_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='derived_depth',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='derived_height',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='derived_width',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
