# Generated by Django 2.2.1 on 2019-06-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20190628_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_store',
            field=models.BooleanField(default=False),
        ),
    ]
