# Generated by Django 2.0.6 on 2018-12-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20181228_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cof',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
