# Generated by Django 2.0.6 on 2018-12-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_auto_20181228_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
