# Generated by Django 2.0.6 on 2018-07-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_auto_20180711_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='units_available',
            field=models.IntegerField(default=0),
        ),
    ]
