# Generated by Django 2.2.1 on 2019-06-29 19:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_product_in_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bb_sku',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
