# Generated by Django 3.0.2 on 2020-01-22 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_auto_20200121_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dae_file_url',
            new_name='derived_dae_file',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='gltf_file_url',
            new_name='derived_gltf_file',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='mtl_file_url',
            new_name='derived_mtl_file',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='obj_file_url',
            new_name='derived_obj_file',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stl_file_url',
            new_name='derived_stl_file',
        ),
    ]
