# Generated by Django 2.0.6 on 2018-07-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_supplierproduct_units_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproduct',
            name='unit',
            field=models.CharField(choices=[('Square Foot', 'Square Foot'), ('Linear Foot', 'Linear Foot'), ('Cubic Foot', 'Cubic Foot'), ('Each', 'Each')], max_length=50),
        ),
    ]
