# Generated by Django 3.0.2 on 2020-01-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_auto_20200122_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='derived_dae_file',
            field=models.FileField(blank=True, null=True, upload_to='derived'),
        ),
        migrations.AlterField(
            model_name='product',
            name='derived_gltf_file',
            field=models.FileField(blank=True, null=True, upload_to='derived'),
        ),
        migrations.AlterField(
            model_name='product',
            name='derived_mtl_file',
            field=models.FileField(blank=True, null=True, upload_to='derived'),
        ),
        migrations.AlterField(
            model_name='product',
            name='derived_obj_file',
            field=models.FileField(blank=True, null=True, upload_to='derived'),
        ),
        migrations.AlterField(
            model_name='product',
            name='derived_stl_file',
            field=models.FileField(blank=True, null=True, upload_to='derived'),
        ),
    ]
