# Generated by Django 3.0.2 on 2020-01-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_auto_20200122_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rvt_file',
            new_name='rfa_file',
        ),
        migrations.AddField(
            model_name='product',
            name='dwg_2d_file',
            field=models.FileField(blank=True, null=True, upload_to='dwg_2d/'),
        ),
        migrations.AddField(
            model_name='product',
            name='dwg_3d_file',
            field=models.FileField(blank=True, null=True, upload_to='dwg_3d/'),
        ),
        migrations.AddField(
            model_name='product',
            name='dxf_file',
            field=models.FileField(blank=True, null=True, upload_to='dxf/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='derived_dae_file',
            field=models.FileField(blank=True, null=True, upload_to='derived/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='derived_gltf_file',
            field=models.FileField(blank=True, null=True, upload_to='derived/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='derived_mtl_file',
            field=models.FileField(blank=True, null=True, upload_to='derived/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='derived_obj_file',
            field=models.FileField(blank=True, null=True, upload_to='derived/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='derived_stl_file',
            field=models.FileField(blank=True, null=True, upload_to='derived/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='light_commercial_warranty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=1200),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('SF', 'SF'), ('EACH', 'Each')], default='SF', max_length=10),
        ),
    ]
