# Generated by Django 2.0.6 on 2018-07-12 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_auto_20180711_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierproduct',
            name='unit',
        ),
        migrations.AddField(
            model_name='producttype',
            name='unit',
            field=models.CharField(choices=[('Square Foot', 'Square Foot'), ('Linear Foot', 'Linear Foot'), ('Cubic Foot', 'Cubic Foot'), ('Each', 'Each')], default='not asssigned', max_length=50),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='units_per_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.ProductType'),
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='application',
        ),
        migrations.AddField(
            model_name='producttype',
            name='application',
            field=models.ManyToManyField(to='Products.Application'),
        ),
    ]
