# Generated by Django 3.0.2 on 2020-01-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_auto_20200122_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='derived_bin_file',
            field=models.FileField(blank=True, null=True, upload_to='derived/'),
        ),
    ]
