# Generated by Django 2.0.6 on 2018-07-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_auto_20180712_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='application',
        ),
        migrations.AddField(
            model_name='product',
            name='application',
            field=models.ManyToManyField(to='Products.Application'),
        ),
    ]
