# Generated by Django 3.0.2 on 2020-01-31 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_product_derived_bin_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dae_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='derived_bin_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='derived_dae_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='derived_gltf_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='derived_mtl_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='derived_obj_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='derived_stl_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gltf_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stl_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='three_json',
        ),
        migrations.AddField(
            model_name='product',
            name='derived_gbl',
            field=models.FileField(blank=True, null=True, upload_to='derived'),
        ),
    ]
