# Generated by Django 3.0.2 on 2020-01-31 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_auto_20200131_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='derived_gbl',
            field=models.FileField(blank=True, null=True, upload_to='derived/'),
        ),
    ]
