# Generated by Django 3.0.2 on 2020-01-31 02:53

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_auto_20200131_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='derived_obj',
            field=models.FileField(blank=True, null=True, upload_to=Products.models.get_3d_return_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='derived_gbl',
            field=models.FileField(blank=True, null=True, upload_to=Products.models.get_3d_return_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='dwg_2d_file',
            field=models.FileField(blank=True, null=True, upload_to=Products.models.get_3d_return_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='dwg_3d_file',
            field=models.FileField(blank=True, null=True, upload_to=Products.models.get_3d_return_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='dxf_file',
            field=models.FileField(blank=True, null=True, upload_to=Products.models.get_3d_return_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='ipt_file',
            field=models.FileField(blank=True, null=True, upload_to=Products.models.get_3d_return_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='mtl_file',
            field=models.FileField(blank=True, null=True, upload_to=Products.models.get_3d_return_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='obj_file',
            field=models.FileField(blank=True, null=True, upload_to=Products.models.get_3d_return_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='rfa_file',
            field=models.FileField(blank=True, null=True, upload_to=Products.models.get_3d_return_path),
        ),
    ]
