# Generated by Django 3.0.2 on 2020-01-31 03:38

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_auto_20200131_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mtl_file',
            field=models.FileField(blank=True, null=True, upload_to=Products.models.get_3d_return_path),
        ),
    ]
