# Generated by Django 3.0.2 on 2020-01-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0014_auto_20200131_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='room_scene',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='swatch_image',
            field=models.ImageField(upload_to='swatches/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tiling_image',
            field=models.ImageField(blank=True, null=True, upload_to='tiles/'),
        ),
    ]
