# Generated by Django 3.0.2 on 2020-02-04 18:58

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0015_auto_20200131_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='derived_obj',
        ),
        migrations.AddField(
            model_name='product',
            name='_dwg_2d_file',
            field=models.FileField(blank=True, null=True, upload_to=Products.models.get_3d_return_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_dwg_3d_file',
            field=models.FileField(blank=True, null=True, upload_to=Products.models.get_3d_return_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_dxf_file',
            field=models.FileField(blank=True, null=True, upload_to=Products.models.get_3d_return_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_ipt_file',
            field=models.FileField(blank=True, null=True, upload_to=Products.models.get_3d_return_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_mtl_file',
            field=models.FileField(blank=True, null=True, upload_to=Products.models.get_3d_return_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_obj_file',
            field=models.FileField(blank=True, null=True, upload_to=Products.models.get_3d_return_path),
        ),
        migrations.AddField(
            model_name='product',
            name='_rfa_file',
            field=models.FileField(blank=True, null=True, upload_to=Products.models.get_3d_return_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='dwg_2d_file',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dwg_3d_file',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dxf_file',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ipt_file',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mtl_file',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='obj_file',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rfa_file',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
