# Generated by Django 3.0.2 on 2020-02-05 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0016_auto_20200204_1858'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('manufacturer', 'manufacturer_sku')},
        ),
    ]
