# Generated by Django 3.0.2 on 2020-02-05 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0017_auto_20200205_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufacturer_collection',
        ),
    ]
