# Generated by Django 3.0.2 on 2020-02-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0018_remove_product_manufacturer_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer_collection',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
