# Generated by Django 3.0.2 on 2020-02-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0019_product_manufacturer_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='derived_center',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
