# Generated by Django 3.0.2 on 2020-02-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0020_product_derived_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='derived_center',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
