# Generated by Django 3.0.2 on 2020-02-05 05:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0021_auto_20200205_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='derived_center',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=3),
        ),
    ]
