# Generated by Django 3.0.2 on 2020-02-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0022_auto_20200205_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(editable=False, max_length=60, null=True),
        ),
    ]
