# Generated by Django 3.0.2 on 2020-02-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0023_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hash_value',
            field=models.CharField(blank=True, max_length=1200, null=True, unique=True),
        ),
    ]
